using Jularr.Web.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Jularr.Web.Data.Migrations;

// What an approved request explicitly asks for, independent of Monitoring: a Work (the whole title) or single units (episodes). A pending request has no rows;
// the rows count while the request is open. Raw SQL like the other single-purpose tables; open requests that predate it are given their Work row.
[DbContext(typeof(AppDbContext))]
[Migration("20261008190000_RequestTargets")]
public partial class RequestTargets : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE "RequestTargets" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                "RequestId" TEXT NOT NULL,
                "WorkId" UUID NOT NULL,
                "TargetKind" SMALLINT NOT NULL,
                "TargetId" UUID NOT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL,
                CONSTRAINT "PK_RequestTargets" PRIMARY KEY ("Id"),
                CONSTRAINT "UQ_RequestTargets_Target" UNIQUE ("RequestId", "TargetKind", "TargetId"),
                CONSTRAINT "CK_RequestTargets_TargetKind" CHECK ("TargetKind" BETWEEN 0 AND 6),
                CONSTRAINT "FK_RequestTargets_AcquisitionRequests" FOREIGN KEY ("RequestId") REFERENCES "AcquisitionRequests" ("Id"),
                CONSTRAINT "FK_RequestTargets_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id")
            );
            CREATE INDEX "IX_RequestTargets_TargetId" ON "RequestTargets" ("TargetId");
            CREATE INDEX "IX_RequestTargets_WorkId" ON "RequestTargets" ("WorkId");

            CREATE FUNCTION pg_temp.request_work(workId text, payload text) RETURNS uuid LANGUAGE plpgsql AS $$
            BEGIN
                RETURN COALESCE(workId::uuid, (payload::jsonb ->> 'workId')::uuid);
            EXCEPTION WHEN others THEN
                RETURN NULL;
            END
            $$;

            INSERT INTO "RequestTargets" ("RequestId", "WorkId", "TargetKind", "TargetId", "CreatedAt")
            SELECT x."Id", x."Work", 0, x."Work", now()
            FROM (SELECT r."Id", pg_temp.request_work(r."WorkId", r."PayloadJson") AS "Work"
                  FROM "AcquisitionRequests" r
                  WHERE r."Kind" IN ('movie', 'book', 'lightNovel', 'manga', 'music')
                    AND r."Status" IN ('approved', 'searching', 'downloading', 'importing')) x
            WHERE x."Work" IS NOT NULL AND EXISTS (SELECT 1 FROM "Works" w WHERE w."Id" = x."Work")
            ON CONFLICT DO NOTHING;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("""DROP TABLE "RequestTargets";""");
}
