using Jularr.Web.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Jularr.Web.Data.Migrations;

/// <summary>
/// The one canonical Monitoring state. <c>WorkMonitoring</c> holds only explicit decisions on a Work or one of its structure nodes (a missing row means
/// Inherit); <c>WorkMonitoringSources</c> holds the monitored relation sources (a person with roles, a studio, a collection, an artist). Raw SQL like the
/// other single-purpose tables; the target id is the canonical id of the node, so no row ever points at a second hierarchy.
/// </summary>
[DbContext(typeof(AppDbContext))]
[Migration("20261008140000_CanonicalMonitoring")]
public partial class CanonicalMonitoring : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE "WorkMonitoring" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                "WorkId" UUID NOT NULL,
                "Kind" SMALLINT NOT NULL,
                "TargetId" UUID NOT NULL,
                "Monitored" BOOLEAN NOT NULL,
                "UpdatedAt" TIMESTAMPTZ NOT NULL,
                CONSTRAINT "PK_WorkMonitoring" PRIMARY KEY ("Id"),
                CONSTRAINT "UQ_WorkMonitoring_TargetId" UNIQUE ("TargetId"),
                CONSTRAINT "CK_WorkMonitoring_Kind" CHECK ("Kind" BETWEEN 0 AND 5),
                CONSTRAINT "FK_WorkMonitoring_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id")
            );
            CREATE INDEX "IX_WorkMonitoring_WorkId" ON "WorkMonitoring" ("WorkId");

            CREATE TABLE "WorkMonitoringSources" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                "Kind" SMALLINT NOT NULL,
                "SourceKey" TEXT NOT NULL,
                "Label" TEXT NOT NULL,
                "Roles" TEXT[] NULL,
                "AddedByProfileId" TEXT NOT NULL,
                "UpdatedAt" TIMESTAMPTZ NOT NULL,
                CONSTRAINT "PK_WorkMonitoringSources" PRIMARY KEY ("Id"),
                CONSTRAINT "UQ_WorkMonitoringSources_Kind_SourceKey" UNIQUE ("Kind", "SourceKey"),
                CONSTRAINT "CK_WorkMonitoringSources_Kind" CHECK ("Kind" BETWEEN 0 AND 3)
            );
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""DROP TABLE IF EXISTS "WorkMonitoringSources"; DROP TABLE IF EXISTS "WorkMonitoring";""");
    }
}
