using Jularr.Web.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Jularr.Web.Data.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20261009194000_RequestSubmissionUsage")]
public sealed class RequestSubmissionUsage : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // No FK to Requests: deleting a request must not refund a rolling submission quota.
        migrationBuilder.Sql("""
            CREATE TABLE "RequestSubmissionUsage" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RequestId" UUID NOT NULL UNIQUE,
                "RequestedByProfileId" TEXT NOT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL,
                "DecidedByProfileId" TEXT NULL
            );
            CREATE INDEX "IX_RequestSubmissionUsage_ProfileCreated" ON "RequestSubmissionUsage" ("RequestedByProfileId", "CreatedAt");
            INSERT INTO "RequestSubmissionUsage" ("RequestId", "RequestedByProfileId", "CreatedAt", "DecidedByProfileId")
            SELECT "Id"::uuid, "RequestedByProfileId", "CreatedAt"::timestamptz, "DecidedByProfileId" FROM "AcquisitionRequests";
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""DROP TABLE "RequestSubmissionUsage";""");
    }
}
