// <auto-generated />
using System;
using Jularr.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Reflection;

#nullable disable

namespace Jularr.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            var migration = new GamesFoundation();
            var buildTargetModel = typeof(GamesFoundation).GetMethod(
                "BuildTargetModel",
                BindingFlags.Instance | BindingFlags.NonPublic)
                ?? throw new InvalidOperationException("Previous migration target model is unavailable.");
            buildTargetModel.Invoke(migration, [modelBuilder]);

            modelBuilder.Model.RemoveEntityType("Jularr.Web.Features.Library.MediaAnalysisStream");
            modelBuilder.Model.RemoveEntityType("Jularr.Web.Features.Library.MediaAnalysis");
            modelBuilder.Model.RemoveEntityType("Jularr.Web.Features.Library.MediaFile");

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaAsset", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("Kind").HasColumnType("integer");
                    b.Property<Guid?>("WorkEpisodeId").HasColumnType("uuid");
                    b.Property<Guid>("WorkId").HasColumnType("uuid");
                    b.Property<Guid>("WorkVersionId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("WorkEpisodeId");
                    b.HasIndex("WorkId", "WorkEpisodeId", "Kind");
                    b.HasIndex("WorkVersionId", "Kind").IsUnique();
                    b.ToTable("MediaAssets", t =>
                        t.HasCheckConstraint("CK_MediaAssets_Kind", "\"Kind\" >= 0 AND \"Kind\" <= 5"));
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaTechnicalAnalysis", b =>
                {
                    b.Property<Guid>("MediaFileId").HasColumnType("uuid").HasColumnName("StoredFileId");
                    b.Property<DateTime>("AnalyzedAt").HasColumnType("timestamp with time zone");
                    b.Property<int?>("BitDepth").HasColumnType("integer");
                    b.Property<string>("Container").HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("Diagnostic").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<double?>("DurationSeconds").HasColumnType("double precision");
                    b.Property<string>("DynamicRange").HasMaxLength(24).HasColumnType("character varying(24)");
                    b.Property<int?>("Height").HasColumnType("integer");
                    b.Property<string>("PixelFormat").HasMaxLength(40).HasColumnType("character varying(40)");
                    b.Property<int>("ProbeVersion").HasColumnType("integer");
                    b.Property<string>("SourceFingerprint").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("SourceLastWriteTimeUtc").IsRequired().HasColumnType("text");
                    b.Property<long>("SourceSizeBytes").HasColumnType("bigint");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<string>("VideoCodec").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("VideoProfile").HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<int?>("Width").HasColumnType("integer");
                    b.HasKey("MediaFileId");
                    b.HasIndex("Status", "ProbeVersion");
                    b.ToTable("MediaTechnicalAnalyses");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaTrack", b =>
                {
                    b.Property<Guid>("MediaFileId").HasColumnType("uuid").HasColumnName("StoredFileId");
                    b.Property<int>("StreamIndex").HasColumnType("integer");
                    b.Property<string>("ChannelLayout").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<int?>("Channels").HasColumnType("integer");
                    b.Property<string>("Codec").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<bool>("IsDefault").HasColumnType("boolean");
                    b.Property<bool>("IsForced").HasColumnType("boolean");
                    b.Property<int>("Kind").HasColumnType("integer");
                    b.Property<string>("Language").HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string>("Title").HasMaxLength(300).HasColumnType("character varying(300)");
                    b.HasKey("MediaFileId", "StreamIndex");
                    b.ToTable("MediaTracks");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.StoredFile", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("DiscoveredAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("EpisodeId").HasColumnType("uuid");
                    b.Property<string>("LastWriteTimeUtc").IsRequired().HasColumnType("text");
                    b.Property<Guid>("LibraryRootId").HasColumnType("uuid");
                    b.Property<Guid?>("MediaAssetId").HasColumnType("uuid");
                    b.Property<string>("Path").IsRequired().HasMaxLength(2048).HasColumnType("character varying(2048)");
                    b.Property<long>("SizeBytes").HasColumnType("bigint");
                    b.HasKey("Id");
                    b.HasIndex("EpisodeId");
                    b.HasIndex("MediaAssetId");
                    b.HasIndex("Path").IsUnique();
                    b.HasIndex("LibraryRootId", "EpisodeId");
                    b.ToTable("StoredFiles", t =>
                        t.HasCheckConstraint("CK_StoredFiles_SizeBytes", "\"SizeBytes\" >= 0"));
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaAsset", b =>
                {
                    b.HasOne("Jularr.Web.Features.MediaCore.WorkEpisode", null)
                        .WithMany().HasForeignKey("WorkEpisodeId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("Jularr.Web.Features.MediaCore.Work", null)
                        .WithMany().HasForeignKey("WorkId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("Jularr.Web.Features.MediaCore.WorkVersion", null)
                        .WithMany().HasForeignKey("WorkVersionId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaTechnicalAnalysis", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.StoredFile", null)
                        .WithOne()
                        .HasForeignKey("Jularr.Web.Features.Library.MediaTechnicalAnalysis", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaTrack", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.StoredFile", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany().HasForeignKey("EpisodeId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("Jularr.Web.Features.Library.LibraryRoot", null)
                        .WithMany().HasForeignKey("LibraryRootId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Jularr.Web.Features.Library.MediaAsset", null)
                        .WithMany().HasForeignKey("MediaAssetId").OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }

    }
}
