// <auto-generated />
using System;
using Jularr.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Reflection;

#nullable disable

namespace Jularr.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            var migration = new GamesFoundation();
            var buildTargetModel = typeof(GamesFoundation).GetMethod(
                "BuildTargetModel",
                BindingFlags.Instance | BindingFlags.NonPublic)
                ?? throw new InvalidOperationException("Previous migration target model is unavailable.");
            buildTargetModel.Invoke(migration, [modelBuilder]);

            modelBuilder.Model.RemoveEntityType("Jularr.Web.Features.Library.MediaAnalysisStream");
            modelBuilder.Model.RemoveEntityType("Jularr.Web.Features.Library.MediaAnalysis");
            modelBuilder.Model.RemoveEntityType("Jularr.Web.Features.Library.MediaFile");
            modelBuilder.Model.RemoveEntityType("Jularr.Web.Features.ReaderPreferences.ReaderPreference");

            modelBuilder.Entity("Jularr.Web.Features.Library.LibraryRoot", b =>
                {
                    b.Property<int>("PlacementPolicy").HasColumnType("integer");
                    b.ToTable("LibraryRoots", t =>
                        t.HasCheckConstraint("CK_LibraryRoots_PlacementPolicy", "\"PlacementPolicy\" >= 0 AND \"PlacementPolicy\" <= 3"));
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.LibraryRootContentAssignment", b =>
                {
                    b.Property<Guid>("LibraryRootId").HasColumnType("uuid");
                    b.Property<int>("ContentType").HasColumnType("integer");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsDefault").HasColumnType("boolean");
                    b.HasKey("LibraryRootId", "ContentType");
                    b.HasIndex("ContentType").IsUnique().HasFilter("\"IsDefault\" = TRUE");
                    b.HasIndex("ContentType", "IsDefault");
                    b.ToTable("LibraryRootContentAssignments", t =>
                        t.HasCheckConstraint("CK_LibraryRootContentAssignments_ContentType", "\"ContentType\" >= 1 AND \"ContentType\" <= 8"));
                    b.HasOne("Jularr.Web.Features.Library.LibraryRoot", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.ReaderPreferences.ReaderPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("AutoContinueChapters")
                        .HasColumnType("boolean");

                    b.Property<double?>("AutoScrollSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("BackgroundAssetId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double?>("BackgroundIntensity")
                        .HasColumnType("double precision");

                    b.Property<string>("BackgroundMotionMode")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("BookmarkColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BookmarkStyle")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ChapterStyle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FontFamily")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("FontSizeRem")
                        .HasColumnType("double precision");

                    b.Property<bool?>("FuriganaEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GenreArtworkEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GenreTheme")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<bool?>("Hyphenation")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageColorScheme")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool?>("ImageCropBorders")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ImageFirstPageAlone")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageFit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ImageFlowMode")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ImagePageDirection")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("ImagePageGapPx")
                        .HasColumnType("integer");

                    b.Property<bool?>("ImageSharpen")
                        .HasColumnType("boolean");

                    b.Property<int?>("ImageZoomPercent")
                        .HasColumnType("integer");

                    b.Property<double?>("LineHeight")
                        .HasColumnType("double precision");

                    b.Property<string>("PageTransition")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("PaperStyle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("ParagraphIndent")
                        .HasColumnType("boolean");

                    b.Property<double?>("ParagraphSpacingEm")
                        .HasColumnType("double precision");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ReadingMode")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool?>("ShowIllustrations")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ShowPageNumbers")
                        .HasColumnType("boolean");

                    b.Property<string>("TextAlignment")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int?>("TextWidthPx")
                        .HasColumnType("integer");

                    b.Property<double?>("ThemeBlurPx")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeBrightness")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeContrast")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeEffectStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeGrainStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeParallaxStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeSaturation")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeTextBackdropStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeTintStrength")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThemeVignetteStrength")
                        .HasColumnType("double precision");

                    b.Property<bool?>("TtsAutoContinueChapters")
                        .HasColumnType("boolean");

                    b.Property<double?>("TtsPitch")
                        .HasColumnType("double precision");

                    b.Property<string>("TtsProviderId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<double?>("TtsRate")
                        .HasColumnType("double precision");

                    b.Property<string>("TtsVoiceIds")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<double?>("TtsVolume")
                        .HasColumnType("double precision");

                    b.Property<bool?>("TwoPageSpread")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "ScopeKey")
                        .IsUnique();

                    b.ToTable("ReaderPreferences");
                });


            modelBuilder.Entity("Jularr.Web.Features.Library.MediaAsset", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("Kind").HasColumnType("integer");
                    b.Property<Guid?>("WorkEpisodeId").HasColumnType("uuid");
                    b.Property<Guid>("WorkId").HasColumnType("uuid");
                    b.Property<Guid>("WorkVersionId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("WorkEpisodeId");
                    b.HasIndex("WorkId", "WorkEpisodeId", "Kind");
                    b.HasIndex("WorkVersionId", "Kind").IsUnique();
                    b.ToTable("MediaAssets", t =>
                        t.HasCheckConstraint("CK_MediaAssets_Kind", "\"Kind\" >= 0 AND \"Kind\" <= 5"));
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaTechnicalAnalysis", b =>
                {
                    b.Property<Guid>("MediaFileId").HasColumnType("uuid").HasColumnName("StoredFileId");
                    b.Property<DateTime>("AnalyzedAt").HasColumnType("timestamp with time zone");
                    b.Property<int?>("BitDepth").HasColumnType("integer");
                    b.Property<string>("Container").HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("Diagnostic").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<double?>("DurationSeconds").HasColumnType("double precision");
                    b.Property<string>("DynamicRange").HasMaxLength(24).HasColumnType("character varying(24)");
                    b.Property<int?>("Height").HasColumnType("integer");
                    b.Property<string>("PixelFormat").HasMaxLength(40).HasColumnType("character varying(40)");
                    b.Property<int>("ProbeVersion").HasColumnType("integer");
                    b.Property<string>("SourceFingerprint").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("SourceLastWriteTimeUtc").IsRequired().HasColumnType("text");
                    b.Property<long>("SourceSizeBytes").HasColumnType("bigint");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<string>("VideoCodec").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("VideoProfile").HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<int?>("Width").HasColumnType("integer");
                    b.HasKey("MediaFileId");
                    b.HasIndex("Status", "ProbeVersion");
                    b.ToTable("MediaTechnicalAnalyses");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaTrack", b =>
                {
                    b.Property<Guid>("MediaFileId").HasColumnType("uuid").HasColumnName("StoredFileId");
                    b.Property<int>("StreamIndex").HasColumnType("integer");
                    b.Property<string>("ChannelLayout").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<int?>("Channels").HasColumnType("integer");
                    b.Property<string>("Codec").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<bool>("IsDefault").HasColumnType("boolean");
                    b.Property<bool>("IsForced").HasColumnType("boolean");
                    b.Property<int>("Kind").HasColumnType("integer");
                    b.Property<string>("Language").HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string>("Title").HasMaxLength(300).HasColumnType("character varying(300)");
                    b.HasKey("MediaFileId", "StreamIndex");
                    b.ToTable("MediaTracks");
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.StoredFile", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("DiscoveredAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("EpisodeId").HasColumnType("uuid");
                    b.Property<string>("LastWriteTimeUtc").IsRequired().HasColumnType("text");
                    b.Property<Guid>("LibraryRootId").HasColumnType("uuid");
                    b.Property<Guid?>("MediaAssetId").HasColumnType("uuid");
                    b.Property<string>("Path").IsRequired().HasMaxLength(2048).HasColumnType("character varying(2048)");
                    b.Property<long>("SizeBytes").HasColumnType("bigint");
                    b.HasKey("Id");
                    b.HasIndex("EpisodeId");
                    b.HasIndex("MediaAssetId");
                    b.HasIndex("Path").IsUnique();
                    b.HasIndex("LibraryRootId", "EpisodeId");
                    b.ToTable("StoredFiles", t =>
                        t.HasCheckConstraint("CK_StoredFiles_SizeBytes", "\"SizeBytes\" >= 0"));
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaAsset", b =>
                {
                    b.HasOne("Jularr.Web.Features.MediaCore.WorkEpisode", null)
                        .WithMany().HasForeignKey("WorkEpisodeId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("Jularr.Web.Features.MediaCore.Work", null)
                        .WithMany().HasForeignKey("WorkId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("Jularr.Web.Features.MediaCore.WorkVersion", null)
                        .WithMany().HasForeignKey("WorkVersionId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaTechnicalAnalysis", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.StoredFile", null)
                        .WithOne()
                        .HasForeignKey("Jularr.Web.Features.Library.MediaTechnicalAnalysis", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.MediaTrack", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jularr.Web.Features.Library.StoredFile", b =>
                {
                    b.HasOne("Jularr.Web.Features.Library.Episode", null)
                        .WithMany().HasForeignKey("EpisodeId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("Jularr.Web.Features.Library.LibraryRoot", null)
                        .WithMany().HasForeignKey("LibraryRootId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Jularr.Web.Features.Library.MediaAsset", null)
                        .WithMany().HasForeignKey("MediaAssetId").OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }

    }
}
