namespace Jularr.Web.Features.MediaCore;

/// <summary>A language-dependent text field of a Work (#820). Language-neutral facts live on <see cref="WorkMetadataFacts"/> instead.</summary>
public enum WorkLocalizedField
{
    /// <summary>The display title in the locale.</summary>
    Title = 0,

    /// <summary>The synopsis.</summary>
    Overview = 1,

    Tagline = 2,

    /// <summary>One genre name per row, ordered by position; the provider localizes the names.</summary>
    Genre = 3,

    /// <summary>One YouTube video key per row, ordered by position; the provider lists trailers per language.</summary>
    Trailer = 4
}

/// <summary>
/// Where a localized value came from. Provider-localized values and Jularr-generated translations are distinct classes (#820):
/// a machine translation of a provider's English synopsis never presents itself as that provider's German synopsis.
/// </summary>
public enum WorkMetadataValueOrigin
{
    /// <summary>Supplied by the provider for exactly this locale.</summary>
    ProviderLocalized = 0,

    /// <summary>Entered or corrected by the owner.</summary>
    OwnerEntered = 1,

    /// <summary>Taken from another stored value of the Work (another locale or a local source).</summary>
    Derived = 2,

    /// <summary>Translated or generated by Jularr or a configured translation provider.</summary>
    MachineTranslated = 3
}

public enum WorkCreditKind
{
    Cast = 0,
    Crew = 1
}

/// <summary>A canonical artwork slot of any Work, independent of media type and provider.</summary>
public enum WorkArtworkSlot
{
    Poster = 0,
    Backdrop = 1,
    Logo = 2
}

/// <summary>Order in which the metadata spool works; a lower value runs first (#820 priority ladder).</summary>
public enum WorkMetadataRefreshPriority
{
    /// <summary>A profile has the Work open.</summary>
    Interactive = 0,

    /// <summary>Requested or monitored and not in the library yet.</summary>
    Requested = 10,

    /// <summary>Imported, local or in progress.</summary>
    Imported = 20,

    /// <summary>The rest of the durable Library.</summary>
    Library = 30,

    /// <summary>A routine refresh of metadata that is already present.</summary>
    Stale = 40
}

/// <summary>Outcome of the last spool run of one <c>(Work, locale)</c>.</summary>
public enum WorkMetadataRefreshStatus
{
    /// <summary>Not fetched yet, or a transient failure that will be retried with backoff.</summary>
    Queued = 0,

    /// <summary>Fetched; refreshed again once stale.</summary>
    Fresh = 1,

    /// <summary>The provider answered that it cannot be fetched (unknown id, no identity); re-probed after a long delay.</summary>
    Failed = 2
}

/// <summary>
/// The language-neutral facts of a Work, one row per Work. Each column's source is recorded in <see cref="WorkFieldProvenance"/> under
/// the field keys of <see cref="WorkMetadataFactFields"/>, so a manual correction is protected by the same ladder as every other field.
/// </summary>
public sealed class WorkMetadataFacts
{
    public long Id { get; set; }

    public Guid WorkId { get; set; }

    public string? OriginalTitle { get; set; }

    /// <summary>ISO 639-1 language of the original production.</summary>
    public string? OriginalLanguage { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public int? RuntimeMinutes { get; set; }

    /// <summary>Provider community rating on a 0-10 scale.</summary>
    public double? Rating { get; set; }

    public int? RatingCount { get; set; }

    /// <summary>Age rating in <see cref="CertificationCountry"/>; certifications are regional, not per language.</summary>
    public string? Certification { get; set; }

    /// <summary>ISO 3166-1 alpha-2 country of <see cref="Certification"/>.</summary>
    public string? CertificationCountry { get; set; }

    public string[] Studios { get; set; } = [];

    /// <summary>ISO 3166-1 alpha-2 codes.</summary>
    public string[] ProductionCountries { get; set; } = [];

    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// One localized value of a Work: <c>(Work, locale, field, position)</c>. List fields (genres, trailers) use one row per position and are
/// replaced as a whole. Provenance is stored beside the value with the same meaning as <see cref="WorkFieldProvenance"/>.
/// </summary>
public sealed class WorkLocalizedValue
{
    public long Id { get; set; }

    public Guid WorkId { get; set; }

    /// <summary>Culture name of the locale the value is for (<c>en</c>, <c>de-DE</c>).</summary>
    public string Locale { get; set; } = "";

    public WorkLocalizedField Field { get; set; }

    public int Position { get; set; }

    public string Value { get; set; } = "";

    public WorkMetadataValueOrigin Origin { get; set; }

    /// <summary>Normalized source key, see <see cref="MetadataFieldSources"/>.</summary>
    public string Source { get; set; } = "";

    /// <summary>The locale a derived or translated value was produced from; null for provider-localized and owner values.</summary>
    public string? SourceLocale { get; set; }

    public string? ProviderExternalId { get; set; }

    public double? Confidence { get; set; }

    public int FallbackPriority { get; set; }

    /// <summary>Owner correction or pin: a provider refresh never replaces it.</summary>
    public bool IsManualOverride { get; set; }

    public DateTime FetchedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}

/// <summary>One cast or key crew member of a Work, in provider billing order.</summary>
public sealed class WorkCredit
{
    public long Id { get; set; }

    public Guid WorkId { get; set; }

    public WorkCreditKind Kind { get; set; }

    public int Position { get; set; }

    public string Name { get; set; } = "";

    /// <summary>The character for cast, the job for crew.</summary>
    public string? Role { get; set; }

    public string Source { get; set; } = "";

    public string? ProviderPersonId { get; set; }

    public DateTime FetchedAt { get; set; }
}

/// <summary>
/// One artwork variant of a Work: at most one per <c>(Work, slot, language)</c>, so retention is bounded by design. The image itself is a
/// Jularr-owned WebP derivative under the local artwork cache, addressed by <see cref="CacheKey"/>; the database never holds image bytes.
/// </summary>
public sealed class WorkArtwork
{
    public long Id { get; set; }

    public Guid WorkId { get; set; }

    public WorkArtworkSlot Slot { get; set; }

    /// <summary>ISO 639-1 language of text in the image; empty for neutral (textless) artwork.</summary>
    public string Language { get; set; } = "";

    public string Source { get; set; } = "";

    /// <summary>The provider's identity of the image (TMDB file path); never served to clients.</summary>
    public string ProviderFilePath { get; set; } = "";

    public int? Width { get; set; }

    public int? Height { get; set; }

    public double? VoteAverage { get; set; }

    public int? VoteCount { get; set; }

    /// <summary>Key of the local derivative; null while it could not be downloaded yet.</summary>
    public string? CacheKey { get; set; }

    public bool IsManualOverride { get; set; }

    public DateTime FetchedAt { get; set; }

    public DateTime? CachedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// The durable metadata spool and freshness record of one <c>(Work, locale)</c>: what runs next, how often it failed and why. Every status
/// carries <see cref="NextAttemptAt"/>, so queued work, backoff, stale refresh and the re-probe of a permanent failure are one due-list.
/// </summary>
public sealed class WorkMetadataRefresh
{
    public long Id { get; set; }

    public Guid WorkId { get; set; }

    public string Locale { get; set; } = "";

    public WorkMetadataRefreshPriority Priority { get; set; }

    public WorkMetadataRefreshStatus Status { get; set; }

    /// <summary>Consecutive failed runs; reset by a successful run.</summary>
    public int Attempts { get; set; }

    public DateTime NextAttemptAt { get; set; }

    public DateTime? LastAttemptAt { get; set; }

    public DateTime? LastSucceededAt { get; set; }

    /// <summary>Root-cause diagnostics of the last failure (exception chain without secrets); null after a success.</summary>
    public string? LastError { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}

/// <summary>The <see cref="WorkFieldProvenance"/> field keys of the <see cref="WorkMetadataFacts"/> columns.</summary>
public static class WorkMetadataFactFields
{
    public const string OriginalTitle = "originalTitle";
    public const string OriginalLanguage = "originalLanguage";
    public const string ReleaseDate = "releaseDate";
    public const string Runtime = "runtime";
    public const string Rating = "rating";
    public const string Certification = "certification";
    public const string Studios = "studios";
    public const string ProductionCountries = "productionCountries";
}
