-- PHASE B WORKING DRAFT PART 2; NOT AN APPROVED BASELINE OR DB MIGRATION.
-- Execute only after the reviewed Part 1 against a disposable clean PostgreSQL DB.
-- Exact seed IDs, authorization contracts, provider/AI/notification models remain review items.
BEGIN;

CREATE TABLE "ProgressPositionTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_ProgressPositionTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_ProgressPositionTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_ProgressPositionTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_ProgressPositionTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "ProgressPositionTypes" ("Id", "Key")
VALUES
    (1, 'time'),
    (2, 'reading'),
    (3, 'game');

-- Total-subtype participation without business triggers:
-- Generated nullable parent references become non-null for the selected type;
-- deferrable reciprocal FKs require its matching detail by COMMIT and reject wrong detail types.
CREATE TABLE "MediaProgress" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "WorkEpisodeId" bigint,
    "WorkChapterId" bigint,
    "WorkTrackId" bigint,
    "WorkEditionId" bigint,
    "ProgressPositionTypeId" smallint NOT NULL,
    "TimePositionId" bigint GENERATED ALWAYS AS
        (CASE WHEN "ProgressPositionTypeId"=1 THEN "Id" ELSE NULL::bigint END) STORED,
    "ReadingPositionId" bigint GENERATED ALWAYS AS
        (CASE WHEN "ProgressPositionTypeId"=2 THEN "Id" ELSE NULL::bigint END) STORED,
    "GamePositionId" bigint GENERATED ALWAYS AS
        (CASE WHEN "ProgressPositionTypeId"=3 THEN "Id" ELSE NULL::bigint END) STORED,
    "IsCompleted" boolean NOT NULL DEFAULT false,
    "Revision" bigint NOT NULL DEFAULT 1,
    "LastActivityAt" timestamptz NOT NULL DEFAULT now(),
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_MediaProgress" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaProgress_Id_Type" UNIQUE ("Id","ProgressPositionTypeId"),
    CONSTRAINT "UX_MediaProgress_Id_WorkId" UNIQUE ("Id", "WorkId"),
    CONSTRAINT "FK_MediaProgress_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaProgress_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaProgress_WorkEpisodes" FOREIGN KEY ("WorkEpisodeId","WorkId") REFERENCES "WorkEpisodes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaProgress_WorkChapters" FOREIGN KEY ("WorkChapterId","WorkId") REFERENCES "WorkChapters" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaProgress_WorkTracks" FOREIGN KEY ("WorkTrackId","WorkId") REFERENCES "WorkTracks" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaProgress_WorkEditions" FOREIGN KEY ("WorkEditionId","WorkId") REFERENCES "WorkEditions" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaProgress_ProgressPositionTypes" FOREIGN KEY ("ProgressPositionTypeId") REFERENCES "ProgressPositionTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_MediaProgress_TargetCount" CHECK (num_nonnulls("WorkEpisodeId","WorkChapterId","WorkTrackId","WorkEditionId") <= 1),
    CONSTRAINT "CK_MediaProgress_PositionType" CHECK ("ProgressPositionTypeId" IN (1,2,3)),
    CONSTRAINT "CK_MediaProgress_Revision" CHECK ("Revision" >= 1)
);
CREATE UNIQUE INDEX "UX_MediaProgress_Profile_ExactTarget" ON "MediaProgress"
    ("ProfileId","WorkId","WorkEpisodeId","WorkChapterId","WorkTrackId","WorkEditionId") NULLS NOT DISTINCT;
CREATE INDEX "IX_MediaProgress_Continue" ON "MediaProgress" ("ProfileId","LastActivityAt" DESC,"Id" DESC);

CREATE TABLE "TimeProgressPositions" (
    "MediaProgressId" bigint NOT NULL,
    "ProgressPositionTypeId" smallint GENERATED ALWAYS AS (1::smallint) STORED,
    "PositionMs" bigint NOT NULL DEFAULT 0,
    "DurationMs" bigint,
    CONSTRAINT "PK_TimeProgressPositions" PRIMARY KEY ("MediaProgressId"),
    CONSTRAINT "FK_TimeProgressPositions_MediaProgress" FOREIGN KEY ("MediaProgressId","ProgressPositionTypeId")
        REFERENCES "MediaProgress" ("Id","ProgressPositionTypeId") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "CK_TimeProgressPositions_Positive" CHECK ("PositionMs" >= 0 AND ("DurationMs" IS NULL OR "DurationMs" >= 0))
);
CREATE TABLE "ReadingProgressPositions" (
    "MediaProgressId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "ProgressPositionTypeId" smallint GENERATED ALWAYS AS (2::smallint) STORED,
    "ReaderContentId" bigint,
    "PageIndex" integer,
    "TextLocator" jsonb,
    "ProgressPermille" smallint,
    CONSTRAINT "PK_ReadingProgressPositions" PRIMARY KEY ("MediaProgressId"),
    CONSTRAINT "FK_ReadingProgressPositions_MediaProgress" FOREIGN KEY ("MediaProgressId","ProgressPositionTypeId")
        REFERENCES "MediaProgress" ("Id","ProgressPositionTypeId") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "FK_ReadingProgressPositions_ProgressWork" FOREIGN KEY ("MediaProgressId", "WorkId")
        REFERENCES "MediaProgress" ("Id", "WorkId") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "CK_ReadingProgressPositions_Page" CHECK ("PageIndex" IS NULL OR "PageIndex" >= 0),
    CONSTRAINT "CK_ReadingProgressPositions_Permille" CHECK ("ProgressPermille" IS NULL OR "ProgressPermille" BETWEEN 0 AND 1000)
);
CREATE TABLE "GameProgressPositions" (
    "MediaProgressId" bigint NOT NULL,
    "ProgressPositionTypeId" smallint GENERATED ALWAYS AS (3::smallint) STORED,
    "PlayedMs" bigint NOT NULL DEFAULT 0,
    "ProgressPercent" numeric(5,2),
    CONSTRAINT "PK_GameProgressPositions" PRIMARY KEY ("MediaProgressId"),
    CONSTRAINT "FK_GameProgressPositions_MediaProgress" FOREIGN KEY ("MediaProgressId","ProgressPositionTypeId")
        REFERENCES "MediaProgress" ("Id","ProgressPositionTypeId") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "CK_GameProgressPositions_Played" CHECK ("PlayedMs" >= 0),
    CONSTRAINT "CK_GameProgressPositions_Percent" CHECK ("ProgressPercent" IS NULL OR "ProgressPercent" BETWEEN 0 AND 100)
);
ALTER TABLE "MediaProgress" ADD CONSTRAINT "FK_MediaProgress_TimeProgressPositions"
    FOREIGN KEY ("TimePositionId") REFERENCES "TimeProgressPositions" ("MediaProgressId") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "MediaProgress" ADD CONSTRAINT "FK_MediaProgress_ReadingProgressPositions"
    FOREIGN KEY ("ReadingPositionId") REFERENCES "ReadingProgressPositions" ("MediaProgressId") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "MediaProgress" ADD CONSTRAINT "FK_MediaProgress_GameProgressPositions"
    FOREIGN KEY ("GamePositionId") REFERENCES "GameProgressPositions" ("MediaProgressId") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
-- Due to both directions, insert/update parent and its exact detail in ONE SQL transaction.
-- Offline checkpoints need an idempotent event contract in the Phase-B decision register.

CREATE TABLE "WatchlistEntries" (
    "ProfileId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "AddedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_WatchlistEntries" PRIMARY KEY ("ProfileId","WorkId"),
    CONSTRAINT "FK_WatchlistEntries_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WatchlistEntries_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_WatchlistEntries_Newest" ON "WatchlistEntries" ("ProfileId","AddedAt" DESC,"WorkId" DESC);

CREATE TABLE "Collections" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "Name" text NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Collections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Collections_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_Collections_Name" CHECK (length(btrim("Name")) > 0)
);
CREATE INDEX "IX_Collections_ProfileId" ON "Collections" ("ProfileId");

CREATE TABLE "CollectionWorks" (
    "CollectionId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "AddedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_CollectionWorks" PRIMARY KEY ("CollectionId","WorkId"),
    CONSTRAINT "FK_CollectionWorks_Collections" FOREIGN KEY ("CollectionId") REFERENCES "Collections" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CollectionWorks_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ProfileRatings" (
    "ProfileId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "Rating" numeric(4,2) NOT NULL,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ProfileRatings" PRIMARY KEY ("ProfileId","WorkId"),
    CONSTRAINT "FK_ProfileRatings_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProfileRatings_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_ProfileRatings_Rating" CHECK ("Rating" BETWEEN 0 AND 10)
);

-- Composite FK to MediaAssets(Id,WorkId) forbids a history event that claims the
-- wrong WorkId for the actual versioned playable Asset.
CREATE TABLE "MediaPlaybackHistory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "MediaAssetId" bigint,
    "StartedAt" timestamptz NOT NULL,
    "EndedAt" timestamptz,
    CONSTRAINT "PK_MediaPlaybackHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaPlaybackHistory_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaPlaybackHistory_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaPlaybackHistory_MediaAssets" FOREIGN KEY ("MediaAssetId","WorkId") REFERENCES "MediaAssets" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "CK_MediaPlaybackHistory_Time" CHECK ("EndedAt" IS NULL OR "EndedAt" >= "StartedAt")
);
CREATE INDEX "IX_MediaPlaybackHistory_Profile_Start" ON "MediaPlaybackHistory" ("ProfileId","StartedAt" DESC,"Id" DESC);

-- A stored file must belong to the same MediaAsset, and that MediaAsset
-- must belong to the Work identified by the session; no disconnected IDs.
CREATE TABLE "PlaybackSessions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "MediaAssetId" bigint,
    "StoredFileId" bigint,
    "DeviceKey" text,
    "PlaybackModeKey" text NOT NULL,
    "StartedAt" timestamptz NOT NULL DEFAULT now(),
    "LastActiveAt" timestamptz,
    "EndedAt" timestamptz,
    CONSTRAINT "PK_PlaybackSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlaybackSessions_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PlaybackSessions_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PlaybackSessions_MediaAssets" FOREIGN KEY ("MediaAssetId","WorkId") REFERENCES "MediaAssets" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_PlaybackSessions_StoredFiles" FOREIGN KEY ("StoredFileId","MediaAssetId") REFERENCES "StoredFiles" ("Id","MediaAssetId") ON DELETE RESTRICT,
    CONSTRAINT "CK_PlaybackSessions_FileRequiresAsset" CHECK ("StoredFileId" IS NULL OR "MediaAssetId" IS NOT NULL),
    CONSTRAINT "CK_PlaybackSessions_Ended" CHECK ("EndedAt" IS NULL OR "EndedAt" >= "StartedAt")
);
CREATE INDEX "IX_PlaybackSessions_Profile_Started" ON "PlaybackSessions" ("ProfileId","StartedAt" DESC,"Id" DESC);

CREATE TABLE "ImageTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_ImageTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_ImageTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_ImageTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_ImageTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "ImageTypes" ("Id", "Key")
VALUES
    (1, 'cover'),
    (2, 'banner'),
    (3, 'poster'),
    (4, 'backdrop'),
    (5, 'logo'),
    (6, 'screenshot'),
    (7, 'title_screen');
-- Legal target pairings are defined separately from the fixed image kinds.
CREATE TABLE "ImageTargetKindTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_ImageTargetKindTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_ImageTargetKindTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_ImageTargetKindTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_ImageTargetKindTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "ImageTargetKindTypes" ("Id", "Key")
VALUES
    (1, 'work'),
    (2, 'work_chapter'),
    (3, 'media_chapter');

CREATE TABLE "ImageTypeTargets" (
    "ImageTypeId" smallint NOT NULL,
    "ImageTargetKindTypeId" smallint NOT NULL,
    CONSTRAINT "PK_ImageTypeTargets" PRIMARY KEY ("ImageTypeId","ImageTargetKindTypeId"),
    CONSTRAINT "FK_ImageTypeTargets_ImageTypes" FOREIGN KEY ("ImageTypeId") REFERENCES "ImageTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ImageTypeTargets_ImageTargetKindTypes" FOREIGN KEY ("ImageTargetKindTypeId") REFERENCES "ImageTargetKindTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Images" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StorageKey" text NOT NULL,
    "Sha256" bytea,
    "MimeType" text NOT NULL,
    "Width" integer,
    "Height" integer,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Images" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_Images_StorageKey" UNIQUE ("StorageKey"),
    CONSTRAINT "CK_Images_Dimensions" CHECK (
        ("Width" IS NULL AND "Height" IS NULL)
        OR ("Width" IS NOT NULL AND "Height" IS NOT NULL AND "Width" > 0 AND "Height" > 0))
);

CREATE TABLE "MediaChapters" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MediaAssetId" bigint NOT NULL,
    "StartMs" bigint NOT NULL,
    "EndMs" bigint NOT NULL,
    "OrderIndex" integer NOT NULL,
    "DisplayName" text,
    CONSTRAINT "PK_MediaChapters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaChapters_MediaAssets" FOREIGN KEY ("MediaAssetId") REFERENCES "MediaAssets" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_MediaChapters_Asset_Order" UNIQUE ("MediaAssetId","OrderIndex"),
    CONSTRAINT "CK_MediaChapters_Time" CHECK ("StartMs" >= 0 AND "EndMs" > "StartMs")
);
CREATE INDEX "IX_MediaChapters_Asset_Start" ON "MediaChapters" ("MediaAssetId","StartMs","Id");

CREATE TABLE "ImageAssignments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ImageId" bigint NOT NULL,
    "ImageTypeId" smallint NOT NULL,
    "ImageTargetKindTypeId" smallint NOT NULL,
    "WorkId" bigint,
    "WorkChapterId" bigint,
    "MediaChapterId" bigint,
    "UiLocaleId" bigint,
    "Region" varchar(16),
    "Priority" integer NOT NULL DEFAULT 0,
    "IsManual" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ImageAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ImageAssignments_Images" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ImageAssignments_ImageTypeTargets" FOREIGN KEY ("ImageTypeId","ImageTargetKindTypeId")
        REFERENCES "ImageTypeTargets" ("ImageTypeId","ImageTargetKindTypeId") ON DELETE RESTRICT,
    CONSTRAINT "FK_ImageAssignments_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ImageAssignments_WorkChapters" FOREIGN KEY ("WorkChapterId") REFERENCES "WorkChapters" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ImageAssignments_MediaChapters" FOREIGN KEY ("MediaChapterId") REFERENCES "MediaChapters" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ImageAssignments_UiLocales" FOREIGN KEY ("UiLocaleId") REFERENCES "UiLocales" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_ImageAssignments_OneTarget" CHECK (num_nonnulls("WorkId","WorkChapterId","MediaChapterId")=1),
    CONSTRAINT "CK_ImageAssignments_ValidKind" CHECK (
        ("ImageTargetKindTypeId"=1 AND "WorkId" IS NOT NULL) OR
        ("ImageTargetKindTypeId"=2 AND "WorkChapterId" IS NOT NULL) OR
        ("ImageTargetKindTypeId"=3 AND "MediaChapterId" IS NOT NULL))
);
CREATE INDEX "IX_ImageAssignments_Work" ON "ImageAssignments" ("WorkId","ImageTypeId","UiLocaleId","Priority" DESC,"Id") WHERE "WorkId" IS NOT NULL;
CREATE INDEX "IX_ImageAssignments_WorkChapter" ON "ImageAssignments" ("WorkChapterId","ImageTypeId","Id") WHERE "WorkChapterId" IS NOT NULL;
CREATE INDEX "IX_ImageAssignments_MediaChapter" ON "ImageAssignments" ("MediaChapterId","ImageTypeId","Id") WHERE "MediaChapterId" IS NOT NULL;

CREATE TABLE "MediaSegmentTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_MediaSegmentTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaSegmentTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_MediaSegmentTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_MediaSegmentTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "MediaSegmentTypes" ("Id", "Key")
VALUES
    (1, 'intro'),
    (2, 'recap'),
    (3, 'outro'),
    (4, 'credits'),
    (5, 'preview');

CREATE TABLE "MediaSegmentSourceTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_MediaSegmentSourceTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaSegmentSourceTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_MediaSegmentSourceTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_MediaSegmentSourceTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "MediaSegmentSourceTypes" ("Id", "Key")
VALUES
    (1, 'manual'),
    (2, 'imported'),
    (3, 'provider'),
    (4, 'detector');
CREATE TABLE "MediaSegments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MediaAssetId" bigint NOT NULL,
    "MediaSegmentTypeId" smallint NOT NULL,
    "MediaSegmentSourceTypeId" smallint NOT NULL,
    "StartMs" bigint NOT NULL,
    "EndMs" bigint NOT NULL,
    "IsManualOverride" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_MediaSegments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaSegments_MediaAssets" FOREIGN KEY ("MediaAssetId") REFERENCES "MediaAssets" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaSegments_MediaSegmentTypes" FOREIGN KEY ("MediaSegmentTypeId") REFERENCES "MediaSegmentTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaSegments_MediaSegmentSourceTypes" FOREIGN KEY ("MediaSegmentSourceTypeId") REFERENCES "MediaSegmentSourceTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_MediaSegments_Time" CHECK ("StartMs" >= 0 AND "EndMs" > "StartMs")
);
CREATE INDEX "IX_MediaSegments_Asset_Start" ON "MediaSegments" ("MediaAssetId","StartMs","Id");
-- No unique-on-kind: intro/outro/credits/recap can repeat or overlap.

CREATE TABLE "MediaDetectionTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_MediaDetectionTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaDetectionTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_MediaDetectionTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_MediaDetectionTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "MediaDetectionTypes" ("Id", "Key")
VALUES
    (1, 'audio_fingerprint');
CREATE TABLE "MediaDetectionStatusTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_MediaDetectionStatusTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaDetectionStatusTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_MediaDetectionStatusTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_MediaDetectionStatusTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "MediaDetectionStatusTypes" ("Id", "Key")
VALUES
    (1, 'running'),
    (2, 'succeeded'),
    (3, 'failed'),
    (4, 'cancelled');
CREATE TABLE "MediaDetectionRuns" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MediaAssetId" bigint NOT NULL,
    "MediaDetectionTypeId" smallint NOT NULL,
    "MediaDetectionStatusTypeId" smallint NOT NULL,
    "InputFingerprint" text NOT NULL,
    "DetectorVersion" text NOT NULL,
    "MatchCount" integer,
    "StartedAt" timestamptz NOT NULL DEFAULT now(),
    "FinishedAt" timestamptz,
    "ErrorCode" text,
    CONSTRAINT "PK_MediaDetectionRuns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaDetectionRuns_MediaAssets" FOREIGN KEY ("MediaAssetId") REFERENCES "MediaAssets" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaDetectionRuns_MediaDetectionTypes" FOREIGN KEY ("MediaDetectionTypeId") REFERENCES "MediaDetectionTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaDetectionRuns_MediaDetectionStatusTypes" FOREIGN KEY ("MediaDetectionStatusTypeId") REFERENCES "MediaDetectionStatusTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_MediaDetectionRuns_MatchCount" CHECK ("MatchCount" IS NULL OR "MatchCount" >= 0),
    CONSTRAINT "CK_MediaDetectionRuns_Input" CHECK (length(btrim("InputFingerprint")) > 0 AND length(btrim("DetectorVersion")) > 0),
    CONSTRAINT "CK_MediaDetectionRuns_Time" CHECK ("FinishedAt" IS NULL OR "FinishedAt" >= "StartedAt"),
    CONSTRAINT "CK_MediaDetectionRuns_Result" CHECK (
        ("MediaDetectionStatusTypeId" = 1 AND "FinishedAt" IS NULL AND "MatchCount" IS NULL AND "ErrorCode" IS NULL)
        OR ("MediaDetectionStatusTypeId" = 2 AND "FinishedAt" IS NOT NULL AND "MatchCount" IS NOT NULL AND "ErrorCode" IS NULL)
        OR ("MediaDetectionStatusTypeId" = 3 AND "FinishedAt" IS NOT NULL AND "MatchCount" IS NULL
            AND "ErrorCode" IS NOT NULL AND length(btrim("ErrorCode")) > 0)
        OR ("MediaDetectionStatusTypeId" = 4 AND "FinishedAt" IS NOT NULL AND "MatchCount" IS NULL AND "ErrorCode" IS NULL))
);
CREATE INDEX "IX_MediaDetectionRuns_Invariants" ON "MediaDetectionRuns"
    ("MediaAssetId","MediaDetectionTypeId","InputFingerprint","DetectorVersion","StartedAt" DESC);
-- A successful MatchCount=0 is a REAL detection result, not a failure / rerun signal.

CREATE TABLE "ReaderContent" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "WorkEditionId" bigint NOT NULL,
    "ContentRevision" integer NOT NULL DEFAULT 1,
    "StorageKey" text NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ReaderContent" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_ReaderContent_Id_WorkId" UNIQUE ("Id", "WorkId"),
    CONSTRAINT "FK_ReaderContent_WorkEditions" FOREIGN KEY ("WorkEditionId", "WorkId") REFERENCES "WorkEditions" ("Id", "WorkId") ON DELETE RESTRICT,
    CONSTRAINT "UX_ReaderContent_Edition_Revision" UNIQUE ("WorkEditionId","ContentRevision"),
    CONSTRAINT "CK_ReaderContent_Revision" CHECK ("ContentRevision" >= 1)
);
CREATE TABLE "ReaderPages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ReaderContentId" bigint NOT NULL,
    "PageIndex" integer NOT NULL,
    "TextAnchor" text,
    CONSTRAINT "PK_ReaderPages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReaderPages_ReaderContent" FOREIGN KEY ("ReaderContentId") REFERENCES "ReaderContent" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_ReaderPages_Content_PageIndex" UNIQUE ("ReaderContentId","PageIndex"),
    CONSTRAINT "CK_ReaderPages_Index" CHECK ("PageIndex" >= 0)
);
ALTER TABLE "ReadingProgressPositions" ADD CONSTRAINT "FK_ReadingProgressPositions_ReaderContent"
    FOREIGN KEY ("ReaderContentId", "WorkId") REFERENCES "ReaderContent" ("Id", "WorkId") ON DELETE RESTRICT;

CREATE TABLE "ReaderBookmarks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "ReaderContentId" bigint NOT NULL,
    "TextLocator" jsonb NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ReaderBookmarks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReaderBookmarks_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ReaderBookmarks_ReaderContent" FOREIGN KEY ("ReaderContentId") REFERENCES "ReaderContent" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_ReaderBookmarks_Profile" ON "ReaderBookmarks" ("ProfileId","CreatedAt" DESC,"Id" DESC);

CREATE TABLE "ReaderHighlights" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "ReaderContentId" bigint NOT NULL,
    "StartLocator" jsonb NOT NULL,
    "EndLocator" jsonb NOT NULL,
    "Note" text,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ReaderHighlights" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReaderHighlights_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ReaderHighlights_ReaderContent" FOREIGN KEY ("ReaderContentId") REFERENCES "ReaderContent" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UiTranslationMessages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NOT NULL,
    CONSTRAINT "PK_UiTranslationMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_UiTranslationMessages_Key" UNIQUE ("Key")
);
CREATE TABLE "UiTranslations" (
    "UiTranslationMessageId" bigint NOT NULL,
    "UiLocaleId" bigint NOT NULL,
    "Text" text NOT NULL,
    "IsReviewed" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_UiTranslations" PRIMARY KEY ("UiTranslationMessageId","UiLocaleId"),
    CONSTRAINT "FK_UiTranslations_UiTranslationMessages" FOREIGN KEY ("UiTranslationMessageId") REFERENCES "UiTranslationMessages" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_UiTranslations_UiLocales" FOREIGN KEY ("UiLocaleId") REFERENCES "UiLocales" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_UiTranslations_LocaleId" ON "UiTranslations" ("UiLocaleId");

CREATE TABLE "OperationStatusTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_OperationStatusTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_OperationStatusTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_OperationStatusTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_OperationStatusTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "OperationStatusTypes" ("Id", "Key")
VALUES
    (1, 'queued'),
    (2, 'running'),
    (3, 'succeeded'),
    (4, 'failed'),
    (5, 'cancelled'),
    (6, 'interrupted');
CREATE TABLE "Operations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationKindKey" text NOT NULL,
    "OperationStatusTypeId" smallint NOT NULL,
    "IdempotencyKey" text,
    "Input" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "AttemptCount" integer NOT NULL DEFAULT 0,
    "NextAttemptAt" timestamptz,
    "ClaimedBy" text,
    "ClaimedUntil" timestamptz,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "StartedAt" timestamptz,
    "FinishedAt" timestamptz,
    CONSTRAINT "PK_Operations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Operations_OperationStatusTypes" FOREIGN KEY ("OperationStatusTypeId") REFERENCES "OperationStatusTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_Operations_IdempotencyKey" UNIQUE ("IdempotencyKey"),
    CONSTRAINT "CK_Operations_Attempts" CHECK ("AttemptCount" >= 0),
    CONSTRAINT "CK_Operations_ClaimPair" CHECK (("ClaimedBy" IS NULL) = ("ClaimedUntil" IS NULL))
);
CREATE INDEX "IX_Operations_Queue" ON "Operations" ("OperationStatusTypeId","NextAttemptAt","CreatedAt","Id");

CREATE TABLE "OperationLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationId" bigint NOT NULL,
    "EventKey" text NOT NULL,
    "SafeMessage" text,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_OperationLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OperationLogs_Operations" FOREIGN KEY ("OperationId") REFERENCES "Operations" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_OperationLogs_Operation_Created" ON "OperationLogs" ("OperationId","CreatedAt","Id");

CREATE TABLE "ImageGenerationRequests" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "OperationId" bigint,
    "Prompt" text NOT NULL,
    "AcceptedImageId" bigint,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ImageGenerationRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ImageGenerationRequests_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ImageGenerationRequests_Operations" FOREIGN KEY ("OperationId") REFERENCES "Operations" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ImageGenerationRequests_Images" FOREIGN KEY ("AcceptedImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

-- Acquisition/notifications below are minimal provisional source-of-truth shapes.
-- Their complete statuses, policy, subscriptions, channels and provider grants need B decisions.
CREATE TABLE "AcquisitionRequestStatusTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_AcquisitionRequestStatusTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AcquisitionRequestStatusTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_AcquisitionRequestStatusTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_AcquisitionRequestStatusTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "AcquisitionRequestStatusTypes" ("Id", "Key")
VALUES
    (1, 'pending'),
    (2, 'approved'),
    (3, 'searching'),
    (4, 'downloading'),
    (5, 'importing'),
    (6, 'completed'),
    (7, 'rejected'),
    (8, 'failed');
CREATE TABLE "AcquisitionRequests" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "AcquisitionRequestStatusTypeId" smallint NOT NULL,
    "OperationId" bigint,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AcquisitionRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AcquisitionRequests_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequests_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequests_AcquisitionRequestStatusTypes" FOREIGN KEY ("AcquisitionRequestStatusTypeId") REFERENCES "AcquisitionRequestStatusTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequests_Operations" FOREIGN KEY ("OperationId") REFERENCES "Operations" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_AcquisitionRequests_Profile_Created" ON "AcquisitionRequests" ("ProfileId","CreatedAt" DESC,"Id" DESC);

CREATE TABLE "Notifications" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" bigint NOT NULL,
    "MessageKey" text NOT NULL,
    "Data" jsonb,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "ReadAt" timestamptz,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_Notifications_Account_Created" ON "Notifications" ("AccountId","CreatedAt" DESC,"Id" DESC);

COMMIT;
