-- PHASE B DRAFT 08: canonical cross-language Learning units/cards/FSRS.
-- Source: docs/LEARNING_LANGUAGES.md (ONE card/review state owner), not a
-- duplicate Curriculum/LearnerCourseProgress table from draft 05.
-- BCP-47 source/target languages are independent of UiLocale.
-- RUN only against isolated disposable PostgreSQL, after Parts 01..07.
BEGIN;

CREATE TABLE "Terms" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LanguageTag" varchar(35) NOT NULL,
    "CanonicalForm" text NOT NULL,
    "Reading" text,
    "DictionaryMeaning" text,
    "MeaningLanguageTag" varchar(35),
    CONSTRAINT "PK_Terms" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Terms_Form" CHECK (length(btrim("CanonicalForm")) > 0)
);
CREATE INDEX "IX_Terms_Language_Form" ON "Terms" ("LanguageTag","CanonicalForm","Id");
-- Terms are shared lexical catalog facts, never learner Saved/Known/FSRS state.

-- Kind is a closed, code-owned smallint enum, not a free-form client string.
-- Existing C# LearningUnitKind: Word=1, Sentence=2, Script=3. Confirm target
-- enum : byte and exact seed IDs once, in the canonical B01 seed manifest.
CREATE TABLE "LearningUnitKindTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningUnitKindTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningUnitKindTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "LearningUnits" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TermId" bigint,
    "LearningUnitKindTypeId" smallint NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearningUnits" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningUnits_TermId" UNIQUE ("TermId"),
    CONSTRAINT "FK_LearningUnits_Terms" FOREIGN KEY ("TermId") REFERENCES "Terms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningUnits_LearningUnitKindTypes" FOREIGN KEY ("LearningUnitKindTypeId") REFERENCES "LearningUnitKindTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "LearningVariantRoleTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningVariantRoleTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningVariantRoleTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "LearningVariantSourceTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningVariantSourceTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningVariantSourceTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "LearningVariants" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LearningUnitId" bigint NOT NULL,
    "LanguageTag" varchar(35) NOT NULL,
    "LearningVariantRoleTypeId" smallint NOT NULL,
    "LearningVariantSourceTypeId" smallint NOT NULL,
    "Text" text NOT NULL,
    "Reading" text,
    CONSTRAINT "PK_LearningVariants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LearningVariants_LearningUnits" FOREIGN KEY ("LearningUnitId") REFERENCES "LearningUnits" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningVariants_LearningVariantRoleTypes" FOREIGN KEY ("LearningVariantRoleTypeId") REFERENCES "LearningVariantRoleTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningVariants_LearningVariantSourceTypes" FOREIGN KEY ("LearningVariantSourceTypeId") REFERENCES "LearningVariantSourceTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningVariants_Text" CHECK (length(btrim("Text")) > 0)
);
CREATE INDEX "IX_LearningVariants_Unit_Language" ON "LearningVariants" ("LearningUnitId","LanguageTag");

CREATE TABLE "LearningCourses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "SourceLanguage" varchar(35) NOT NULL,
    "TargetLanguage" varchar(35) NOT NULL,
    "DisplayName" text NOT NULL,
    "IsPrimary" boolean NOT NULL DEFAULT false,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearningCourses" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningCourses_Id_ProfileId" UNIQUE ("Id","ProfileId"),
    CONSTRAINT "UX_LearningCourses_Profile_Languages" UNIQUE ("ProfileId","SourceLanguage","TargetLanguage"),
    CONSTRAINT "FK_LearningCourses_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningCourses_Language" CHECK (length(btrim("SourceLanguage")) > 0 AND length(btrim("TargetLanguage")) > 0)
);
CREATE UNIQUE INDEX "UX_LearningCourses_Primary_Source" ON "LearningCourses" ("ProfileId","SourceLanguage") WHERE "IsPrimary" = true;

CREATE TABLE "LearningCardModeTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningCardModeTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningCardModeTypes_Key" UNIQUE ("Key")
);
-- Recognition is the required unit-anchor card; others exist per enabled modes.
CREATE TABLE "LearningCardStateTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningCardStateTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningCardStateTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "LearningCards" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LearningCourseId" bigint NOT NULL,
    "ProfileId" bigint NOT NULL,
    "LearningUnitId" bigint NOT NULL,
    "LearningCardModeTypeId" smallint NOT NULL,
    "LearningCardStateTypeId" smallint NOT NULL,
    "DueAt" timestamptz,
    "StartedAt" timestamptz,
    "LastReviewedAt" timestamptz,
    "FsrsStability" double precision,
    "FsrsDifficulty" double precision,
    "ScheduledDays" integer,
    "ReviewCount" integer NOT NULL DEFAULT 0,
    "QueuePosition" bigint,
    CONSTRAINT "PK_LearningCards" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningCards_Id_ProfileId" UNIQUE ("Id","ProfileId"),
    CONSTRAINT "UX_LearningCards_Course_Unit_Mode" UNIQUE ("LearningCourseId","LearningUnitId","LearningCardModeTypeId"),
    CONSTRAINT "FK_LearningCards_LearningCourses" FOREIGN KEY ("LearningCourseId","ProfileId") REFERENCES "LearningCourses" ("Id","ProfileId") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningCards_LearningUnits" FOREIGN KEY ("LearningUnitId") REFERENCES "LearningUnits" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningCards_Modes" FOREIGN KEY ("LearningCardModeTypeId") REFERENCES "LearningCardModeTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningCards_States" FOREIGN KEY ("LearningCardStateTypeId") REFERENCES "LearningCardStateTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningCards_ReviewCount" CHECK ("ReviewCount" >= 0),
    CONSTRAINT "CK_LearningCards_Stability" CHECK ("FsrsStability" IS NULL OR "FsrsStability" >= 0),
    CONSTRAINT "CK_LearningCards_Difficulty" CHECK ("FsrsDifficulty" IS NULL OR "FsrsDifficulty" BETWEEN 0 AND 10),
    CONSTRAINT "CK_LearningCards_ScheduledDays" CHECK ("ScheduledDays" IS NULL OR "ScheduledDays" >= 0)
);
CREATE INDEX "IX_LearningCards_Course_Due" ON "LearningCards" ("LearningCourseId","DueAt","Id");

CREATE TABLE "LearningCardReviewRatingTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningCardReviewRatingTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningCardReviewRatingTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "LearningCardReviews" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LearningCardId" bigint NOT NULL,
    "ProfileId" bigint NOT NULL,
    "ClientEventId" uuid NOT NULL,
    "LearningCardReviewRatingTypeId" smallint NOT NULL,
    "ReviewedAt" timestamptz NOT NULL DEFAULT now(),
    "ResponseDurationMs" bigint,
    CONSTRAINT "PK_LearningCardReviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LearningCardReviews_LearningCards" FOREIGN KEY ("LearningCardId","ProfileId") REFERENCES "LearningCards" ("Id","ProfileId") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningCardReviews_RatingTypes" FOREIGN KEY ("LearningCardReviewRatingTypeId") REFERENCES "LearningCardReviewRatingTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_LearningCardReviews_Profile_Event" UNIQUE ("ProfileId","ClientEventId"),
    CONSTRAINT "CK_LearningCardReviews_ResponseDuration" CHECK ("ResponseDurationMs" IS NULL OR "ResponseDurationMs" >= 0)
);
CREATE INDEX "IX_LearningCardReviews_Card_Reviewed" ON "LearningCardReviews" ("LearningCardId","ReviewedAt" DESC,"Id" DESC);

CREATE TABLE "LearningContexts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LearningUnitId" bigint NOT NULL,
    "SourceTypeKey" text NOT NULL,
    "SourceKey" text NOT NULL,
    "PositionKey" text,
    "LanguageTag" varchar(35) NOT NULL,
    "SourceText" text NOT NULL,
    CONSTRAINT "PK_LearningContexts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LearningContexts_LearningUnits" FOREIGN KEY ("LearningUnitId") REFERENCES "LearningUnits" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningContexts_Key" CHECK (length(btrim("SourceTypeKey")) > 0 AND length(btrim("SourceKey")) > 0)
);
CREATE INDEX "IX_LearningContexts_Unit" ON "LearningContexts" ("LearningUnitId","Id");
-- LearningCourse (personal directional vocabulary practice) and LearnerCourse
-- (enrolment in published authored curriculum) are intentionally different
-- contracts, but they reuse exactly one LearningUnit / LearningCards / FSRS owner.
-- Curriculum exercises link units explicitly; do NOT duplicate FSRS state.
-- All enum IDs, FSRS compatibility fields, repeated offline events and review
-- invariants require current model/contract tests before Gate B.
COMMIT;
