-- PHASE B DRAFT 07: one Acquisition quality/search/download configuration owner.
-- Derived from Acquisition/Quality/QualityModels.cs and CODEMAPs for
-- Acquisition/Core, Wanted, Selection, Indexers and DownloadClients.
-- One canonical Operations queue. No second job queue and no torrent support.
-- Credentials are opaque, server-owned protected /data references, not secrets.
-- All proposed type seeds and rules require cross-check with actual runtime.
-- RUN ONLY after 01..06 on a disposable new PostgreSQL database.
BEGIN;

CREATE TABLE "AcquisitionQualityProfiles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Key" varchar(120) NOT NULL,
    "Name" text NOT NULL,
    "IsUpgradeAllowed" boolean NOT NULL DEFAULT true,
    "UpgradeCutoffQuality" text,
    "UpgradeMinimumQualitySteps" integer NOT NULL DEFAULT 1,
    "MinimumSizeBytes" bigint,
    "MaximumSizeBytes" bigint,
    "AllowAmbiguousIdentity" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_AcquisitionQualityProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AcquisitionQualityProfiles_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_AcquisitionQualityProfiles_Name" CHECK (length(btrim("Name")) > 0),
    CONSTRAINT "CK_AcquisitionQualityProfiles_UpgradeStep" CHECK ("UpgradeMinimumQualitySteps" >= 1),
    CONSTRAINT "CK_AcquisitionQualityProfiles_Size" CHECK (
        ("MinimumSizeBytes" IS NULL OR "MinimumSizeBytes" >= 0) AND
        ("MaximumSizeBytes" IS NULL OR "MaximumSizeBytes" >= 0) AND
        ("MinimumSizeBytes" IS NULL OR "MaximumSizeBytes" IS NULL OR "MinimumSizeBytes" <= "MaximumSizeBytes"))
);
CREATE TABLE "AcquisitionQualityProfileQualities" (
    "AcquisitionQualityProfileId" bigint NOT NULL,
    "QualityKey" text NOT NULL,
    "IsAllowed" boolean NOT NULL DEFAULT true,
    "QualityOrder" integer NOT NULL,
    CONSTRAINT "PK_AcquisitionQualityProfileQualities" PRIMARY KEY ("AcquisitionQualityProfileId","QualityKey"),
    CONSTRAINT "FK_AcquisitionQualityProfileQualities_Profiles" FOREIGN KEY ("AcquisitionQualityProfileId") REFERENCES "AcquisitionQualityProfiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_AcquisitionQualityProfileQualities_Order" UNIQUE ("AcquisitionQualityProfileId","QualityOrder"),
    CONSTRAINT "CK_AcquisitionQualityProfileQualities_Order" CHECK ("QualityOrder" >= 0)
);
CREATE TABLE "AcquisitionQualityProfileLanguages" (
    "AcquisitionQualityProfileId" bigint NOT NULL,
    "LanguageTag" varchar(35) NOT NULL,
    "Ordinal" integer NOT NULL,
    CONSTRAINT "PK_AcquisitionQualityProfileLanguages" PRIMARY KEY ("AcquisitionQualityProfileId","LanguageTag"),
    CONSTRAINT "FK_AcquisitionQualityProfileLanguages_Profiles" FOREIGN KEY ("AcquisitionQualityProfileId") REFERENCES "AcquisitionQualityProfiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_AcquisitionQualityProfileLanguages_Ordinal" UNIQUE ("AcquisitionQualityProfileId","Ordinal"),
    CONSTRAINT "CK_AcquisitionQualityProfileLanguages_Ordinal" CHECK ("Ordinal" >= 0)
);

CREATE TABLE "AcquisitionRuleFieldTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_AcquisitionRuleFieldTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AcquisitionRuleFieldTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "AcquisitionRuleMatchTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_AcquisitionRuleMatchTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AcquisitionRuleMatchTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "AcquisitionRuleEffectTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_AcquisitionRuleEffectTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AcquisitionRuleEffectTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "AcquisitionQualityProfileRules" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AcquisitionQualityProfileId" bigint NOT NULL,
    "Ordinal" integer NOT NULL,
    "Name" text NOT NULL,
    "AcquisitionRuleFieldTypeId" smallint NOT NULL,
    "AcquisitionRuleMatchTypeId" smallint NOT NULL,
    "AcquisitionRuleEffectTypeId" smallint NOT NULL,
    "MatchValue" text NOT NULL,
    "Score" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AcquisitionQualityProfileRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AcquisitionQualityProfileRules_Profiles" FOREIGN KEY ("AcquisitionQualityProfileId") REFERENCES "AcquisitionQualityProfiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionQualityProfileRules_Fields" FOREIGN KEY ("AcquisitionRuleFieldTypeId") REFERENCES "AcquisitionRuleFieldTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionQualityProfileRules_Matches" FOREIGN KEY ("AcquisitionRuleMatchTypeId") REFERENCES "AcquisitionRuleMatchTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionQualityProfileRules_Effects" FOREIGN KEY ("AcquisitionRuleEffectTypeId") REFERENCES "AcquisitionRuleEffectTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_AcquisitionQualityProfileRules_Order" UNIQUE ("AcquisitionQualityProfileId","Ordinal"),
    CONSTRAINT "CK_AcquisitionQualityProfileRules_Ordinal" CHECK ("Ordinal" >= 0)
);

-- Acquisition-kind defaults are NOT MediaTypes: Anime is a classification of TV
-- and Audiobook is a Book WorkEdition, not another root Work or MediaType.
CREATE TABLE "AcquisitionKindTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_AcquisitionKindTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AcquisitionKindTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "AcquisitionKindDefaultProfiles" (
    "AcquisitionKindTypeId" smallint NOT NULL,
    "AcquisitionQualityProfileId" bigint NOT NULL,
    CONSTRAINT "PK_AcquisitionKindDefaultProfiles" PRIMARY KEY ("AcquisitionKindTypeId"),
    CONSTRAINT "FK_AcquisitionKindDefaultProfiles_Kinds" FOREIGN KEY ("AcquisitionKindTypeId") REFERENCES "AcquisitionKindTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionKindDefaultProfiles_Profiles" FOREIGN KEY ("AcquisitionQualityProfileId") REFERENCES "AcquisitionQualityProfiles" ("Id") ON DELETE RESTRICT
);
CREATE TABLE "WorkAcquisitionQualityProfiles" (
    "WorkId" bigint NOT NULL,
    "AcquisitionQualityProfileId" bigint NOT NULL,
    CONSTRAINT "PK_WorkAcquisitionQualityProfiles" PRIMARY KEY ("WorkId"),
    CONSTRAINT "FK_WorkAcquisitionQualityProfiles_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkAcquisitionQualityProfiles_Profiles" FOREIGN KEY ("AcquisitionQualityProfileId") REFERENCES "AcquisitionQualityProfiles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AcquisitionIndexerTypeTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_AcquisitionIndexerTypeTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AcquisitionIndexerTypeTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "AcquisitionIndexers" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "DisplayName" text NOT NULL,
    "AcquisitionIndexerTypeId" smallint NOT NULL,
    "BaseUrl" text NOT NULL,
    "CredentialStorageKey" text NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "AutomaticSearch" boolean NOT NULL DEFAULT true,
    "InteractiveSearch" boolean NOT NULL DEFAULT true,
    "Priority" integer NOT NULL DEFAULT 0,
    "SearchLimit" integer NOT NULL DEFAULT 100,
    "LastVerifiedAt" timestamptz,
    "CapabilitiesVersion" integer,
    "Capabilities" jsonb,
    CONSTRAINT "PK_AcquisitionIndexers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AcquisitionIndexers_Types" FOREIGN KEY ("AcquisitionIndexerTypeId") REFERENCES "AcquisitionIndexerTypeTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_AcquisitionIndexers_SearchLimit" CHECK ("SearchLimit" BETWEEN 1 AND 1000),
    CONSTRAINT "CK_AcquisitionIndexers_CapabilitiesVersion" CHECK ("CapabilitiesVersion" IS NULL OR "CapabilitiesVersion" > 0)
);
-- Capabilities is an adapter-owned, versioned protocol snapshot; owner options remain typed.
-- Do not send arbitrary query parameters to a provider based on this JSON alone.

CREATE TABLE "AcquisitionIndexerKinds" (
    "AcquisitionIndexerId" uuid NOT NULL,
    "AcquisitionKindTypeId" smallint NOT NULL,
    CONSTRAINT "PK_AcquisitionIndexerKinds" PRIMARY KEY ("AcquisitionIndexerId","AcquisitionKindTypeId"),
    CONSTRAINT "FK_AcquisitionIndexerKinds_Indexers" FOREIGN KEY ("AcquisitionIndexerId") REFERENCES "AcquisitionIndexers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionIndexerKinds_Kinds" FOREIGN KEY ("AcquisitionKindTypeId") REFERENCES "AcquisitionKindTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AcquisitionProfileIndexers" (
    "AcquisitionQualityProfileId" bigint NOT NULL,
    "AcquisitionIndexerId" uuid NOT NULL,
    "IsAllowed" boolean NOT NULL DEFAULT true,
    "IsPreferred" boolean NOT NULL DEFAULT false,
    "IsFallbackOnly" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_AcquisitionProfileIndexers" PRIMARY KEY ("AcquisitionQualityProfileId","AcquisitionIndexerId"),
    CONSTRAINT "FK_AcquisitionProfileIndexers_Profiles" FOREIGN KEY ("AcquisitionQualityProfileId") REFERENCES "AcquisitionQualityProfiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionProfileIndexers_Indexers" FOREIGN KEY ("AcquisitionIndexerId") REFERENCES "AcquisitionIndexers" ("Id") ON DELETE RESTRICT
);
-- Empty allow list means unrestricted. IsAllowed=true rows are a whitelist;
-- if empty vs only IsAllowed=false is meaningful, refine the restriction mode in B.

CREATE TABLE "AcquisitionDownloadClients" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "DisplayName" text NOT NULL,
    "BaseUrl" text NOT NULL,
    "CredentialStorageKey" text NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "Priority" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AcquisitionDownloadClients" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_AcquisitionDownloadClients_BaseUrl" CHECK (length(btrim("BaseUrl")) > 0)
);
-- V1 only SABnzbd/Usenet. Categories are media acquisition kinds, not MediaType roots.
CREATE TABLE "AcquisitionDownloadClientCategories" (
    "AcquisitionDownloadClientId" uuid NOT NULL,
    "AcquisitionKindTypeId" smallint NOT NULL,
    "Category" text,
    CONSTRAINT "PK_AcquisitionDownloadClientCategories" PRIMARY KEY ("AcquisitionDownloadClientId","AcquisitionKindTypeId"),
    CONSTRAINT "FK_AcquisitionDownloadClientCategories_Clients" FOREIGN KEY ("AcquisitionDownloadClientId") REFERENCES "AcquisitionDownloadClients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionDownloadClientCategories_Kinds" FOREIGN KEY ("AcquisitionKindTypeId") REFERENCES "AcquisitionKindTypes" ("Id") ON DELETE RESTRICT
);

-- One external completed-download routing record; lifecycle execution remains
-- in Operations, so this is not another job queue.
CREATE TABLE "AcquisitionDownloadBindings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationId" bigint NOT NULL,
    "AcquisitionDownloadClientId" uuid NOT NULL,
    "ExternalDownloadId" text,
    "AcquisitionKindTypeId" smallint NOT NULL,
    "AcquisitionRequestId" bigint,
    "WorkId" bigint NOT NULL,
    "ImportStateKey" text,
    "LastImportResultCode" text,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AcquisitionDownloadBindings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AcquisitionDownloadBindings_Operations" FOREIGN KEY ("OperationId") REFERENCES "Operations" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionDownloadBindings_Clients" FOREIGN KEY ("AcquisitionDownloadClientId") REFERENCES "AcquisitionDownloadClients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionDownloadBindings_Kinds" FOREIGN KEY ("AcquisitionKindTypeId") REFERENCES "AcquisitionKindTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionDownloadBindings_Requests" FOREIGN KEY ("AcquisitionRequestId","WorkId") REFERENCES "AcquisitionRequests" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionDownloadBindings_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_AcquisitionDownloadBindings_OperationId" UNIQUE ("OperationId")
);
CREATE UNIQUE INDEX "UX_AcquisitionDownloadBindings_Client_External" ON "AcquisitionDownloadBindings"
    ("AcquisitionDownloadClientId","ExternalDownloadId") WHERE "ExternalDownloadId" IS NOT NULL;

COMMIT;
