-- PHASE B DRAFT 13: Learning v2 profile/media/work/content scope overrides.
-- Source: docs/LEARNING_V2.md + current Features/Learning/LearningConfiguration.cs.
-- Apply ONLY after parts 01..12 in an isolated disposable PostgreSQL database.
-- This stores preferences, never alternative card/FSRS/progress facts.
BEGIN;

-- New explicit byte enum bindings use the source-proven values and spellings.
-- Approval of new C# : byte bindings is a separate Gate B/B01 requirement.
CREATE TABLE "LearningModeTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningModeTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningModeTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_LearningModeTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_LearningModeTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "LearningModeTypes" ("Id","Key") VALUES
    (0,'off'),(1,'language_tools'),(2,'study'),(3,'custom');

CREATE TABLE "LearningCapabilityTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningCapabilityTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningCapabilityTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_LearningCapabilityTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_LearningCapabilityTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "LearningCapabilityTypes" ("Id","Key") VALUES
    (1,'language_lookup'),
    (2,'reading_aids'),
    (3,'translation'),
    (4,'ai_explanations'),
    (5,'vocabulary'),
    (6,'reviews'),
    (7,'sentence_practice'),
    (8,'script_trainer'),
    (9,'progress'),
    (10,'home_widget'),
    (11,'content_metrics'),
    (12,'preparation_suggestions'),
    (13,'player_tools'),
    (14,'reader_tools');

-- Learning's Anime / Novel / Book / Manga scope classification is NOT
-- interchangeable with Works.MediaTypeId: Anime is a classification of series.
CREATE TABLE "LearningMediaScopeTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningMediaScopeTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningMediaScopeTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_LearningMediaScopeTypes_Id" CHECK ("Id" BETWEEN 1 AND 255),
    CONSTRAINT "CK_LearningMediaScopeTypes_Key" CHECK (length(btrim("Key")) > 0)
);
INSERT INTO "LearningMediaScopeTypes" ("Id","Key") VALUES
    (1,'anime'),(2,'novel'),(3,'book'),(4,'manga');

-- Profile scope: all nullable targets absent.
-- Media scope: only LearningMediaScopeTypeId filled.
-- Work scope: LearningMediaScopeTypeId + WorkId filled.
-- Content scope: MediaScopeTypeId + WorkId + exactly one canonical unit.
-- A nullable LearningModeTypeId represents Inherit; a row may still contain
-- independent capability overrides without creating a mode override.
CREATE TABLE "LearningScopeOverrides" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "LearningMediaScopeTypeId" smallint,
    "WorkId" bigint,
    "WorkEpisodeId" bigint,
    "WorkChapterId" bigint,
    "LearningModeTypeId" smallint,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearningScopeOverrides" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LearningScopeOverrides_Profiles"
        FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningScopeOverrides_LearningMediaScopeTypes"
        FOREIGN KEY ("LearningMediaScopeTypeId") REFERENCES "LearningMediaScopeTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningScopeOverrides_Works"
        FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningScopeOverrides_WorkEpisodes"
        FOREIGN KEY ("WorkEpisodeId","WorkId") REFERENCES "WorkEpisodes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningScopeOverrides_WorkChapters"
        FOREIGN KEY ("WorkChapterId","WorkId") REFERENCES "WorkChapters" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningScopeOverrides_LearningModeTypes"
        FOREIGN KEY ("LearningModeTypeId") REFERENCES "LearningModeTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningScopeOverrides_ValidScope" CHECK (
        ("LearningMediaScopeTypeId" IS NULL AND "WorkId" IS NULL
            AND "WorkEpisodeId" IS NULL AND "WorkChapterId" IS NULL)
        OR
        ("LearningMediaScopeTypeId" IS NOT NULL AND "WorkId" IS NULL
            AND "WorkEpisodeId" IS NULL AND "WorkChapterId" IS NULL)
        OR
        ("LearningMediaScopeTypeId" IS NOT NULL AND "WorkId" IS NOT NULL
            AND num_nonnulls("WorkEpisodeId","WorkChapterId") <= 1)
    ),
    CONSTRAINT "UX_LearningScopeOverrides_ExactScope"
        UNIQUE NULLS NOT DISTINCT
        ("ProfileId","LearningMediaScopeTypeId","WorkId","WorkEpisodeId","WorkChapterId")
);

CREATE TABLE "LearningCapabilityOverrides" (
    "LearningScopeOverrideId" bigint NOT NULL,
    "LearningCapabilityTypeId" smallint NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearningCapabilityOverrides"
        PRIMARY KEY ("LearningScopeOverrideId","LearningCapabilityTypeId"),
    CONSTRAINT "FK_LearningCapabilityOverrides_LearningScopeOverrides"
        FOREIGN KEY ("LearningScopeOverrideId") REFERENCES "LearningScopeOverrides" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningCapabilityOverrides_LearningCapabilityTypes"
        FOREIGN KEY ("LearningCapabilityTypeId") REFERENCES "LearningCapabilityTypes" ("Id") ON DELETE RESTRICT
);

-- Mode and capability resolution belongs to the authorized Learning read Service.
-- Resolve scope chain broad to narrow, then apply explicit capability overrides
-- broad to narrow. Instance module, Profile.IsLearningEnabled, and permission gates
-- MUST run before this resolver; no child scope may bypass an OFF hard gate.
-- Work/media classification and unit-specific policy are verified by Logic/Service,
-- NOT inferred from the media-scope smallint alone.
COMMIT;
