-- PHASE B TARGET DRAFT, PART 3: selected required domain specialties.
-- NOT an approved baseline; proposed media/credits/music schemas require owner review.
-- Apply after Parts 1 and 2 ONLY to a new disposable PostgreSQL database.
BEGIN;

CREATE TABLE "EditionExternalIdentities" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkEditionId" bigint NOT NULL,
    "ProviderId" bigint NOT NULL,
    "ProviderNamespace" text NOT NULL,
    "ExternalId" text NOT NULL,
    CONSTRAINT "PK_EditionExternalIdentities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EditionExternalIdentities_WorkEditions" FOREIGN KEY ("WorkEditionId") REFERENCES "WorkEditions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EditionExternalIdentities_Providers" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_EditionExternalIdentities_ProviderNamespaceId" UNIQUE ("ProviderId","ProviderNamespace","ExternalId")
);
CREATE INDEX "IX_EditionExternalIdentities_WorkEditionId" ON "EditionExternalIdentities" ("WorkEditionId");

CREATE TABLE "People" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DisplayName" text NOT NULL,
    CONSTRAINT "PK_People" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_People_DisplayName" CHECK (length(btrim("DisplayName")) > 0)
);

CREATE TABLE "WorkCreditRoleTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_WorkCreditRoleTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkCreditRoleTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_WorkCreditRoleTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_WorkCreditRoleTypes_Key" CHECK (length(btrim("Key")) > 0)
);
-- Required: author, narrator, illustrator etc.; exact byte enum seed IDs pending.
CREATE TABLE "WorkCredits" (
    "WorkEditionId" bigint NOT NULL,
    "PersonId" bigint NOT NULL,
    "WorkCreditRoleTypeId" smallint NOT NULL,
    "CreditOrder" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_WorkCredits" PRIMARY KEY ("WorkEditionId","PersonId","WorkCreditRoleTypeId"),
    CONSTRAINT "FK_WorkCredits_WorkEditions" FOREIGN KEY ("WorkEditionId") REFERENCES "WorkEditions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkCredits_People" FOREIGN KEY ("PersonId") REFERENCES "People" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkCredits_WorkCreditRoleTypes" FOREIGN KEY ("WorkCreditRoleTypeId") REFERENCES "WorkCreditRoleTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkCredits_Order" CHECK ("CreditOrder" >= 0)
);
CREATE INDEX "IX_WorkCredits_Person" ON "WorkCredits" ("PersonId");

CREATE TABLE "MediaTechnicalAnalyses" (
    "MediaAssetId" bigint NOT NULL,
    "AnalyzedAt" timestamptz NOT NULL DEFAULT now(),
    "DurationMs" bigint,
    "Width" integer,
    "Height" integer,
    "BitRateBps" bigint,
    "SourceFingerprint" text,
    CONSTRAINT "PK_MediaTechnicalAnalyses" PRIMARY KEY ("MediaAssetId"),
    CONSTRAINT "FK_MediaTechnicalAnalyses_MediaAssets" FOREIGN KEY ("MediaAssetId") REFERENCES "MediaAssets" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_MediaTechnicalAnalyses_Duration" CHECK ("DurationMs" IS NULL OR "DurationMs" >= 0),
    CONSTRAINT "CK_MediaTechnicalAnalyses_Dimensions" CHECK (
        ("Width" IS NULL AND "Height" IS NULL)
        OR ("Width" IS NOT NULL AND "Height" IS NOT NULL AND "Width" > 0 AND "Height" > 0)),
    CONSTRAINT "CK_MediaTechnicalAnalyses_Bitrate" CHECK ("BitRateBps" IS NULL OR "BitRateBps" >= 0)
);

-- Music Album is already a Work. Artists and recordings are reusable independent facts,
-- not a new parallel Album root, nor a new MusicWorks table.
CREATE TABLE "MusicArtists" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DisplayName" text NOT NULL,
    "PersonId" bigint,
    CONSTRAINT "PK_MusicArtists" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MusicArtists_People" FOREIGN KEY ("PersonId") REFERENCES "People" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_MusicArtists_Name" CHECK (length(btrim("DisplayName")) > 0)
);

CREATE TABLE "MusicRecordings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DisplayName" text NOT NULL,
    "DurationMs" bigint,
    CONSTRAINT "PK_MusicRecordings" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_MusicRecordings_Name" CHECK (length(btrim("DisplayName")) > 0),
    CONSTRAINT "CK_MusicRecordings_Duration" CHECK ("DurationMs" IS NULL OR "DurationMs" >= 0)
);

CREATE TABLE "MusicRecordingArtists" (
    "MusicRecordingId" bigint NOT NULL,
    "MusicArtistId" bigint NOT NULL,
    CONSTRAINT "PK_MusicRecordingArtists" PRIMARY KEY ("MusicRecordingId","MusicArtistId"),
    CONSTRAINT "FK_MusicRecordingArtists_MusicRecordings" FOREIGN KEY ("MusicRecordingId") REFERENCES "MusicRecordings" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MusicRecordingArtists_MusicArtists" FOREIGN KEY ("MusicArtistId") REFERENCES "MusicArtists" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_MusicRecordingArtists_Artist" ON "MusicRecordingArtists" ("MusicArtistId");

CREATE TABLE "WorkTrackRecordings" (
    "WorkTrackId" bigint NOT NULL,
    "MusicRecordingId" bigint NOT NULL,
    CONSTRAINT "PK_WorkTrackRecordings" PRIMARY KEY ("WorkTrackId"),
    CONSTRAINT "FK_WorkTrackRecordings_WorkTracks" FOREIGN KEY ("WorkTrackId") REFERENCES "WorkTracks" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkTrackRecordings_MusicRecordings" FOREIGN KEY ("MusicRecordingId") REFERENCES "MusicRecordings" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_WorkTrackRecordings_MusicRecording" ON "WorkTrackRecordings" ("MusicRecordingId");

-- Artist/Album relation currently proposed, subject to required music credits semantics.
CREATE TABLE "WorkMusicArtists" (
    "WorkId" bigint NOT NULL,
    "MusicArtistId" bigint NOT NULL,
    CONSTRAINT "PK_WorkMusicArtists" PRIMARY KEY ("WorkId","MusicArtistId"),
    CONSTRAINT "FK_WorkMusicArtists_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkMusicArtists_MusicArtists" FOREIGN KEY ("MusicArtistId") REFERENCES "MusicArtists" ("Id") ON DELETE RESTRICT
);

COMMIT;
