-- PHASE B DRAFT 15: one canonical AI settings/catalog/usage persistence.
-- Approved contract: docs/mockups/admin-ai/SPEC.md; existing Features/Ai
-- AiProfileSettings, AiOperations, AiUsageStore, AiModelCatalogStore.
-- No second job/operation queue and no second generated-content ownership.
-- Apply only after 01..14 on a NEW isolated disposable PostgreSQL instance.
BEGIN;
CREATE TABLE "AiServerProviders" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NOT NULL,
    "DisplayName" text NOT NULL,
    "AdapterKey" text NOT NULL,
    "BaseUrl" text,
    "CredentialStorageKey" text,
    "IsEnabled" boolean NOT NULL DEFAULT false,
    "Priority" integer NOT NULL DEFAULT 0,
    "TimeoutSeconds" integer NOT NULL DEFAULT 60,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AiServerProviders" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AiServerProviders_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_AiServerProviders_Key" CHECK (length(btrim("Key")) BETWEEN 1 AND 120),
    CONSTRAINT "CK_AiServerProviders_DisplayName" CHECK (length(btrim("DisplayName")) > 0),
    CONSTRAINT "CK_AiServerProviders_AdapterKey" CHECK (length(btrim("AdapterKey")) > 0),
    CONSTRAINT "CK_AiServerProviders_Timeout" CHECK ("TimeoutSeconds" BETWEEN 5 AND 900)
);

-- This is the ONLY relational server AI model catalog. Provider discovery is
-- cached locally; a remote provider is never queried by UI/list SELECTs.
CREATE TABLE "AiModels" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AiServerProviderId" bigint NOT NULL,
    "NativeModelId" text NOT NULL,
    "DisplayName" text,
    "Capabilities" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "ContextWindowTokens" integer,
    "MaxOutputTokens" integer,
    "IsEnabled" boolean NOT NULL DEFAULT false,
    "LastDiscoveredAt" timestamptz,
    CONSTRAINT "PK_AiModels" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AiModels_Provider_Model" UNIQUE ("AiServerProviderId","NativeModelId"),
    CONSTRAINT "FK_AiModels_AiServerProviders"
        FOREIGN KEY ("AiServerProviderId") REFERENCES "AiServerProviders" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_AiModels_NativeModelId" CHECK (length(btrim("NativeModelId")) BETWEEN 1 AND 240),
    CONSTRAINT "CK_AiModels_Capabilities"
        CHECK (jsonb_typeof("Capabilities")='object' AND octet_length("Capabilities"::text)<=16384),
    CONSTRAINT "CK_AiModels_Context" CHECK ("ContextWindowTokens" IS NULL OR "ContextWindowTokens">0),
    CONSTRAINT "CK_AiModels_MaxOutput" CHECK ("MaxOutputTokens" IS NULL OR "MaxOutputTokens">0)
);

-- AiOperations stable task keys are validated by Logic against the source
-- registry, NOT user-selected table/column names. A disabled task may have
-- no selected model. A working task must select a concrete primary model.
CREATE TABLE "AiTaskRoutes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskKey" text NOT NULL,
    "PrimaryAiModelId" bigint,
    "FallbackAiModelId" bigint,
    "IsEnabled" boolean NOT NULL DEFAULT false,
    "ContextBudgetTokens" integer,
    "MaxRetries" integer,
    "TimeoutSeconds" integer,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AiTaskRoutes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AiTaskRoutes_TaskKey" UNIQUE ("TaskKey"),
    CONSTRAINT "FK_AiTaskRoutes_PrimaryAiModels" FOREIGN KEY ("PrimaryAiModelId")
        REFERENCES "AiModels" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AiTaskRoutes_FallbackAiModels" FOREIGN KEY ("FallbackAiModelId")
        REFERENCES "AiModels" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_AiTaskRoutes_TaskKey" CHECK (length(btrim("TaskKey")) BETWEEN 1 AND 120),
    CONSTRAINT "CK_AiTaskRoutes_PrimaryRequired" CHECK (NOT "IsEnabled" OR "PrimaryAiModelId" IS NOT NULL),
    CONSTRAINT "CK_AiTaskRoutes_DistinctModels" CHECK (
        "FallbackAiModelId" IS NULL OR "FallbackAiModelId" IS DISTINCT FROM "PrimaryAiModelId"),
    CONSTRAINT "CK_AiTaskRoutes_Context" CHECK ("ContextBudgetTokens" IS NULL OR "ContextBudgetTokens" BETWEEN 1 AND 200000),
    CONSTRAINT "CK_AiTaskRoutes_Retries" CHECK ("MaxRetries" IS NULL OR "MaxRetries" BETWEEN 0 AND 5),
    CONSTRAINT "CK_AiTaskRoutes_Timeout" CHECK ("TimeoutSeconds" IS NULL OR "TimeoutSeconds" BETWEEN 5 AND 900)
);

-- Profile-owned personal AI configuration is separate from instance-wide
-- AiServerProviders. Never store a raw personal API key in a relational row.
CREATE TABLE "AiTranslationModeTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_AiTranslationModeTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AiTranslationModeTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_AiTranslationModeTypes_Id" CHECK ("Id" BETWEEN 0 AND 255)
);
INSERT INTO "AiTranslationModeTypes" ("Id","Key") VALUES
    (0,'efficient'),(1,'quality'),(2,'maximum');

CREATE TABLE "AiProfileSettings" (
    "ProfileId" bigint NOT NULL,
    "ProviderKey" text NOT NULL DEFAULT 'server',
    "BaseUrl" text,
    "ModelId" text,
    "ImageModelId" text,
    "CredentialStorageKey" text,
    "AiTranslationModeTypeId" smallint NOT NULL DEFAULT 0,
    "ReasoningEffort" text,
    "ServiceTier" text,
    "MaxOutputTokens" integer,
    "DailyTokenBudget" integer,
    "SessionTokenBudget" integer,
    "BudgetWarningPercent" smallint,
    "MaxConcurrentJobs" smallint,
    "ContextBudgetTokens" integer,
    "MaxRetries" integer,
    "TimeoutSeconds" integer,
    "Verbosity" text,
    "FallbackModelEnabled" boolean NOT NULL DEFAULT false,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AiProfileSettings" PRIMARY KEY ("ProfileId"),
    CONSTRAINT "FK_AiProfileSettings_Profiles"
        FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_AiProfileSettings_Provider" CHECK ("ProviderKey" IN ('server','openai-compatible')),
    CONSTRAINT "FK_AiProfileSettings_AiTranslationModeTypes" FOREIGN KEY ("AiTranslationModeTypeId") REFERENCES "AiTranslationModeTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_AiProfileSettings_MaxOutput" CHECK ("MaxOutputTokens" IS NULL OR "MaxOutputTokens" BETWEEN 1 AND 128000),
    CONSTRAINT "CK_AiProfileSettings_DailyBudget" CHECK ("DailyTokenBudget" IS NULL OR "DailyTokenBudget" BETWEEN 1 AND 1000000000),
    CONSTRAINT "CK_AiProfileSettings_SessionBudget" CHECK ("SessionTokenBudget" IS NULL OR "SessionTokenBudget" BETWEEN 1 AND 1000000000),
    CONSTRAINT "CK_AiProfileSettings_Warning" CHECK ("BudgetWarningPercent" IS NULL OR "BudgetWarningPercent" BETWEEN 1 AND 99),
    CONSTRAINT "CK_AiProfileSettings_Concurrency" CHECK ("MaxConcurrentJobs" IS NULL OR "MaxConcurrentJobs" BETWEEN 1 AND 8),
    CONSTRAINT "CK_AiProfileSettings_Context" CHECK ("ContextBudgetTokens" IS NULL OR "ContextBudgetTokens" BETWEEN 1 AND 200000),
    CONSTRAINT "CK_AiProfileSettings_Retries" CHECK ("MaxRetries" IS NULL OR "MaxRetries" BETWEEN 0 AND 5),
    CONSTRAINT "CK_AiProfileSettings_Timeout" CHECK ("TimeoutSeconds" IS NULL OR "TimeoutSeconds" BETWEEN 5 AND 900)
);

CREATE TABLE "AiProfileOperationOverrides" (
    "ProfileId" bigint NOT NULL,
    "OperationKey" text NOT NULL,
    "ModelId" text,
    "ReasoningEffort" text,
    "ContextBudgetTokens" integer,
    "MaxOutputTokens" integer,
    "MaxRetries" integer,
    "TimeoutSeconds" integer,
    "Verbosity" text,
    CONSTRAINT "PK_AiProfileOperationOverrides" PRIMARY KEY ("ProfileId","OperationKey"),
    CONSTRAINT "FK_AiProfileOperationOverrides_AiProfileSettings" FOREIGN KEY ("ProfileId")
        REFERENCES "AiProfileSettings" ("ProfileId") ON DELETE RESTRICT,
    CONSTRAINT "CK_AiProfileOperationOverrides_Operation" CHECK (length(btrim("OperationKey")) BETWEEN 1 AND 120),
    CONSTRAINT "CK_AiProfileOperationOverrides_Context" CHECK ("ContextBudgetTokens" IS NULL OR "ContextBudgetTokens" BETWEEN 1 AND 200000),
    CONSTRAINT "CK_AiProfileOperationOverrides_MaxOutput" CHECK ("MaxOutputTokens" IS NULL OR "MaxOutputTokens" BETWEEN 1 AND 128000),
    CONSTRAINT "CK_AiProfileOperationOverrides_Retries" CHECK ("MaxRetries" IS NULL OR "MaxRetries" BETWEEN 0 AND 5),
    CONSTRAINT "CK_AiProfileOperationOverrides_Timeout" CHECK ("TimeoutSeconds" IS NULL OR "TimeoutSeconds" BETWEEN 5 AND 900),
    CONSTRAINT "CK_AiProfileOperationOverrides_NonEmpty" CHECK (
        num_nonnulls("ModelId","ReasoningEffort","ContextBudgetTokens","MaxOutputTokens",
                     "MaxRetries","TimeoutSeconds","Verbosity") > 0)
);

-- One UTC-day aggregate fact per Profile, provider, model and known task.
-- Metrics are bounded day counters (integer), NEVER credential/token secrets
-- and NEVER resource identity. Server totals are bounded aggregates of these.
CREATE TABLE "AiUsageDaily" (
    "ProfileId" bigint NOT NULL,
    "UtcDay" date NOT NULL,
    "ProviderKey" text NOT NULL,
    "ModelId" text NOT NULL,
    "OperationKey" text NOT NULL,
    "Requests" integer NOT NULL DEFAULT 0,
    "EstimatedRequests" integer NOT NULL DEFAULT 0,
    "InputTokens" integer NOT NULL DEFAULT 0,
    "CachedInputTokens" integer NOT NULL DEFAULT 0,
    "OutputTokens" integer NOT NULL DEFAULT 0,
    "ReasoningOutputTokens" integer NOT NULL DEFAULT 0,
    "EstimatedInputTokens" integer NOT NULL DEFAULT 0,
    "EstimatedOutputTokens" integer NOT NULL DEFAULT 0,
    "ContextTokens" integer NOT NULL DEFAULT 0,
    "CacheHits" integer NOT NULL DEFAULT 0,
    "ResumedChunks" integer NOT NULL DEFAULT 0,
    "Retries" integer NOT NULL DEFAULT 0,
    "Failures" integer NOT NULL DEFAULT 0,
    "Cancellations" integer NOT NULL DEFAULT 0,
    "DurationMs" integer NOT NULL DEFAULT 0,
    "FullContextTokens" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AiUsageDaily"
        PRIMARY KEY ("ProfileId","UtcDay","ProviderKey","ModelId","OperationKey"),
    CONSTRAINT "FK_AiUsageDaily_Profiles"
        FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_AiUsageDaily_ProviderKey" CHECK (length(btrim("ProviderKey"))>0),
    CONSTRAINT "CK_AiUsageDaily_ModelId" CHECK (length(btrim("ModelId"))>0),
    CONSTRAINT "CK_AiUsageDaily_OperationKey" CHECK (length(btrim("OperationKey"))>0),
    CONSTRAINT "CK_AiUsageDaily_Requests" CHECK ("Requests" >= 0),
    CONSTRAINT "CK_AiUsageDaily_EstimatedRequests" CHECK ("EstimatedRequests" >= 0),
    CONSTRAINT "CK_AiUsageDaily_InputTokens" CHECK ("InputTokens" >= 0),
    CONSTRAINT "CK_AiUsageDaily_CachedInputTokens" CHECK ("CachedInputTokens" >= 0),
    CONSTRAINT "CK_AiUsageDaily_OutputTokens" CHECK ("OutputTokens" >= 0),
    CONSTRAINT "CK_AiUsageDaily_ReasoningOutputTokens" CHECK ("ReasoningOutputTokens" >= 0),
    CONSTRAINT "CK_AiUsageDaily_EstimatedInputTokens" CHECK ("EstimatedInputTokens" >= 0),
    CONSTRAINT "CK_AiUsageDaily_EstimatedOutputTokens" CHECK ("EstimatedOutputTokens" >= 0),
    CONSTRAINT "CK_AiUsageDaily_ContextTokens" CHECK ("ContextTokens" >= 0),
    CONSTRAINT "CK_AiUsageDaily_CacheHits" CHECK ("CacheHits" >= 0),
    CONSTRAINT "CK_AiUsageDaily_ResumedChunks" CHECK ("ResumedChunks" >= 0),
    CONSTRAINT "CK_AiUsageDaily_Retries" CHECK ("Retries" >= 0),
    CONSTRAINT "CK_AiUsageDaily_Failures" CHECK ("Failures" >= 0),
    CONSTRAINT "CK_AiUsageDaily_Cancellations" CHECK ("Cancellations" >= 0),
    CONSTRAINT "CK_AiUsageDaily_DurationMs" CHECK ("DurationMs" >= 0),
    CONSTRAINT "CK_AiUsageDaily_FullContextTokens" CHECK ("FullContextTokens" >= 0)
);
CREATE INDEX "IX_AiUsageDaily_Day_Profile"
    ON "AiUsageDaily" ("UtcDay" DESC,"ProfileId");

-- All lengthy AI jobs are existing Operations: no AI queue/claims duplication.
-- Stored generated content belongs to Images/Reader/Works/Translations'
-- canonical domain owners; AiUsageDaily is diagnostic/budget accounting only.
COMMIT;
