-- PHASE B WORKING DRAFT 05: ONE canonical Curriculum and LearnerCourse model.
-- Sources: docs/LEARNING_EXERCISES.md + docs/LEARNING_PROGRESS.md.
-- Existing UUID curriculum identities are a DOCUMENTED exception to ordinary bigint PKs.
-- Do not import the historical 56 migrations, and do not apply to active dev database.
-- Published exercise payload JSONB is a VERSIONED, TYPED renderer payload only, NOT EAV.
BEGIN;

CREATE TABLE "CurriculumBlueprints" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Key" text NOT NULL,
    "Version" integer NOT NULL DEFAULT 1,
    "IsPublished" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_CurriculumBlueprints" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_CurriculumBlueprints_Key_Version" UNIQUE ("Key","Version"),
    CONSTRAINT "CK_CurriculumBlueprints_Version" CHECK ("Version" > 0)
);
CREATE TABLE "CurriculumLevels" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CurriculumBlueprintId" uuid NOT NULL,
    "Ordinal" integer NOT NULL,
    CONSTRAINT "PK_CurriculumLevels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CurriculumLevels_CurriculumBlueprints" FOREIGN KEY ("CurriculumBlueprintId") REFERENCES "CurriculumBlueprints" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_CurriculumLevels_Blueprint_Ordinal" UNIQUE ("CurriculumBlueprintId","Ordinal"),
    CONSTRAINT "CK_CurriculumLevels_Ordinal" CHECK ("Ordinal" > 0)
);
CREATE TABLE "CurriculumChapters" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CurriculumLevelId" uuid NOT NULL,
    "Ordinal" integer NOT NULL,
    CONSTRAINT "PK_CurriculumChapters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CurriculumChapters_CurriculumLevels" FOREIGN KEY ("CurriculumLevelId") REFERENCES "CurriculumLevels" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_CurriculumChapters_Level_Ordinal" UNIQUE ("CurriculumLevelId","Ordinal"),
    CONSTRAINT "CK_CurriculumChapters_Ordinal" CHECK ("Ordinal" > 0)
);
CREATE TABLE "CurriculumLessons" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CurriculumChapterId" uuid NOT NULL,
    "Ordinal" integer NOT NULL,
    CONSTRAINT "PK_CurriculumLessons" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_CurriculumLessons_Chapter_Ordinal" UNIQUE ("CurriculumChapterId","Ordinal"),
    CONSTRAINT "FK_CurriculumLessons_CurriculumChapters" FOREIGN KEY ("CurriculumChapterId") REFERENCES "CurriculumChapters" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_CurriculumLessons_Ordinal" CHECK ("Ordinal" > 0)
);
CREATE TABLE "CurriculumExerciseKindTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_CurriculumExerciseKindTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_CurriculumExerciseKindTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "CurriculumExercisePhaseTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_CurriculumExercisePhaseTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_CurriculumExercisePhaseTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "CurriculumExercises" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CurriculumLessonId" uuid NOT NULL,
    "Key" text NOT NULL,
    "Ordinal" integer NOT NULL,
    "CurriculumExerciseKindTypeId" smallint NOT NULL,
    "CurriculumExercisePhaseTypeId" smallint NOT NULL,
    "IsRequired" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_CurriculumExercises" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_CurriculumExercises_Id_Lesson" UNIQUE ("Id","CurriculumLessonId"),
    CONSTRAINT "FK_CurriculumExercises_CurriculumLessons" FOREIGN KEY ("CurriculumLessonId") REFERENCES "CurriculumLessons" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CurriculumExercises_CurriculumExerciseKindTypes" FOREIGN KEY ("CurriculumExerciseKindTypeId") REFERENCES "CurriculumExerciseKindTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CurriculumExercises_CurriculumExercisePhaseTypes" FOREIGN KEY ("CurriculumExercisePhaseTypeId") REFERENCES "CurriculumExercisePhaseTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_CurriculumExercises_Lesson_Key" UNIQUE ("CurriculumLessonId","Key"),
    CONSTRAINT "UX_CurriculumExercises_Lesson_Ordinal" UNIQUE ("CurriculumLessonId","Ordinal"),
    CONSTRAINT "CK_CurriculumExercises_Ordinal" CHECK ("Ordinal" > 0)
);
CREATE TABLE "CurriculumObjectiveSkillTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_CurriculumObjectiveSkillTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_CurriculumObjectiveSkillTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "CurriculumLessonObjectives" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CurriculumLessonId" uuid NOT NULL,
    "Key" varchar(120) NOT NULL,
    "CurriculumObjectiveSkillTypeId" smallint NOT NULL,
    "Ordinal" integer NOT NULL,
    CONSTRAINT "PK_CurriculumLessonObjectives" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_CurriculumLessonObjectives_Id_Lesson" UNIQUE ("Id","CurriculumLessonId"),
    CONSTRAINT "FK_CurriculumLessonObjectives_CurriculumLessons" FOREIGN KEY ("CurriculumLessonId") REFERENCES "CurriculumLessons" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CurriculumLessonObjectives_CurriculumObjectiveSkillTypes" FOREIGN KEY ("CurriculumObjectiveSkillTypeId") REFERENCES "CurriculumObjectiveSkillTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_CurriculumLessonObjectives_Lesson_Key" UNIQUE ("CurriculumLessonId","Key"),
    CONSTRAINT "UX_CurriculumLessonObjectives_Lesson_Ordinal" UNIQUE ("CurriculumLessonId","Ordinal"),
    CONSTRAINT "CK_CurriculumLessonObjectives_Ordinal" CHECK ("Ordinal" > 0)
);
CREATE TABLE "CurriculumExerciseObjectives" (
    "CurriculumExerciseId" uuid NOT NULL,
    "CurriculumLessonObjectiveId" bigint NOT NULL,
    "CurriculumLessonId" uuid NOT NULL,
    CONSTRAINT "PK_CurriculumExerciseObjectives" PRIMARY KEY ("CurriculumExerciseId","CurriculumLessonObjectiveId"),
    CONSTRAINT "FK_CurriculumExerciseObjectives_CurriculumExercises" FOREIGN KEY ("CurriculumExerciseId","CurriculumLessonId") REFERENCES "CurriculumExercises" ("Id","CurriculumLessonId") ON DELETE RESTRICT,
    CONSTRAINT "FK_CurriculumExerciseObjectives_CurriculumLessonObjectives" FOREIGN KEY ("CurriculumLessonObjectiveId","CurriculumLessonId") REFERENCES "CurriculumLessonObjectives" ("Id","CurriculumLessonId") ON DELETE RESTRICT
);
-- Composite LessonId membership mechanically prevents cross-Lesson exercise mapping.

CREATE TABLE "SharedCourseInstances" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CurriculumBlueprintId" uuid NOT NULL,
    "SourceLanguage" varchar(35) NOT NULL,
    "TargetLanguage" varchar(35) NOT NULL,
    "Title" text NOT NULL,
    "ContentVersion" integer NOT NULL,
    "ContentFingerprint" varchar(64) NOT NULL,
    "IsPublished" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_SharedCourseInstances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SharedCourseInstances_CurriculumBlueprints" FOREIGN KEY ("CurriculumBlueprintId") REFERENCES "CurriculumBlueprints" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_SharedCourseInstances_Fingerprint" UNIQUE ("ContentFingerprint"),
    CONSTRAINT "UX_SharedCourseInstances_Version" UNIQUE ("CurriculumBlueprintId","SourceLanguage","TargetLanguage","ContentVersion"),
    CONSTRAINT "CK_SharedCourseInstances_Version" CHECK ("ContentVersion" >= 1),
    CONSTRAINT "CK_SharedCourseInstances_Fingerprint" CHECK ("ContentFingerprint" ~ '^[a-f0-9]{64}$')
);

CREATE TABLE "SharedCourseExerciseContent" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SharedCourseInstanceId" uuid NOT NULL,
    "CurriculumExerciseId" uuid NOT NULL,
    "SchemaVersion" integer NOT NULL,
    "Payload" jsonb NOT NULL,
    "ContentFingerprint" varchar(64) NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_SharedCourseExerciseContent" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SharedCourseExerciseContent_SharedCourseInstances" FOREIGN KEY ("SharedCourseInstanceId") REFERENCES "SharedCourseInstances" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SharedCourseExerciseContent_CurriculumExercises" FOREIGN KEY ("CurriculumExerciseId") REFERENCES "CurriculumExercises" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_SharedCourseExerciseContent_Instance_Exercise" UNIQUE ("SharedCourseInstanceId","CurriculumExerciseId"),
    CONSTRAINT "CK_SharedCourseExerciseContent_SchemaVersion" CHECK ("SchemaVersion" > 0),
    CONSTRAINT "CK_SharedCourseExerciseContent_Fingerprint" CHECK ("ContentFingerprint" ~ '^[a-f0-9]{64}$')
);
-- Source->Target specialized content is immutable once published; enforce in authorized
-- Logic and transaction plus version tests (not a trigger-based business workflow).

CREATE TABLE "LearnerCourses" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "ProfileId" bigint NOT NULL,
    "SharedCourseInstanceId" uuid NOT NULL,
    "EnrolledAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearnerCourses" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearnerCourses_Id_ProfileId" UNIQUE ("Id","ProfileId"),
    CONSTRAINT "FK_LearnerCourses_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerCourses_SharedCourseInstances" FOREIGN KEY ("SharedCourseInstanceId") REFERENCES "SharedCourseInstances" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_LearnerCourses_Profile_Instance" UNIQUE ("ProfileId","SharedCourseInstanceId")
);
CREATE TABLE "LearnerProgressStatusTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearnerProgressStatusTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearnerProgressStatusTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "LearnerProgressSkipReasonTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearnerProgressSkipReasonTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearnerProgressSkipReasonTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "LearnerCourseProgress" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LearnerCourseId" uuid NOT NULL,
    "CurriculumLevelId" uuid,
    "CurriculumChapterId" uuid,
    "CurriculumLessonId" uuid,
    "CurriculumExerciseId" uuid,
    "LearnerProgressStatusTypeId" smallint NOT NULL,
    "CompletedCount" integer NOT NULL DEFAULT 0,
    "LastScore" numeric(5,4),
    "FirstStartedAt" timestamptz,
    "FirstCompletedAt" timestamptz,
    "LastCompletedAt" timestamptz,
    "LearnerProgressSkipReasonTypeId" smallint,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearnerCourseProgress" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LearnerCourseProgress_LearnerCourses" FOREIGN KEY ("LearnerCourseId") REFERENCES "LearnerCourses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerCourseProgress_Levels" FOREIGN KEY ("CurriculumLevelId") REFERENCES "CurriculumLevels" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerCourseProgress_Chapters" FOREIGN KEY ("CurriculumChapterId") REFERENCES "CurriculumChapters" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerCourseProgress_Lessons" FOREIGN KEY ("CurriculumLessonId") REFERENCES "CurriculumLessons" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerCourseProgress_Exercises" FOREIGN KEY ("CurriculumExerciseId") REFERENCES "CurriculumExercises" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerCourseProgress_LearnerProgressStatusTypes" FOREIGN KEY ("LearnerProgressStatusTypeId") REFERENCES "LearnerProgressStatusTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerCourseProgress_LearnerProgressSkipReasonTypes" FOREIGN KEY ("LearnerProgressSkipReasonTypeId") REFERENCES "LearnerProgressSkipReasonTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearnerCourseProgress_Target" CHECK (num_nonnulls("CurriculumLevelId","CurriculumChapterId","CurriculumLessonId","CurriculumExerciseId") = 1),
    CONSTRAINT "CK_LearnerCourseProgress_Completed" CHECK ("CompletedCount" >= 0),
    CONSTRAINT "CK_LearnerCourseProgress_Score" CHECK ("LastScore" IS NULL OR "LastScore" BETWEEN 0 AND 1)
);
CREATE UNIQUE INDEX "UX_LearnerCourseProgress_Target" ON "LearnerCourseProgress"
    ("LearnerCourseId","CurriculumLevelId","CurriculumChapterId","CurriculumLessonId","CurriculumExerciseId") NULLS NOT DISTINCT;
-- Before signoff enforce target belongs to the LearnerCourse's pinned Blueprint.

CREATE TABLE "LearnerExerciseOutcomeTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearnerExerciseOutcomeTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearnerExerciseOutcomeTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "LearnerExerciseAttempts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LearnerCourseId" uuid NOT NULL,
    "CurriculumExerciseId" uuid NOT NULL,
    "ClientEventId" uuid NOT NULL,
    "LearnerExerciseOutcomeTypeId" smallint NOT NULL,
    "Score" numeric(5,4),
    "UsedHint" boolean NOT NULL DEFAULT false,
    "RevealedAnswer" boolean NOT NULL DEFAULT false,
    "ResponseDurationMs" bigint,
    "OccurredAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearnerExerciseAttempts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LearnerExerciseAttempts_LearnerCourses" FOREIGN KEY ("LearnerCourseId") REFERENCES "LearnerCourses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerExerciseAttempts_CurriculumExercises" FOREIGN KEY ("CurriculumExerciseId") REFERENCES "CurriculumExercises" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearnerExerciseAttempts_LearnerExerciseOutcomeTypes" FOREIGN KEY ("LearnerExerciseOutcomeTypeId") REFERENCES "LearnerExerciseOutcomeTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_LearnerExerciseAttempts_ClientEventId" UNIQUE ("ClientEventId"),
    CONSTRAINT "CK_LearnerExerciseAttempts_Score" CHECK ("Score" IS NULL OR "Score" BETWEEN 0 AND 1),
    CONSTRAINT "CK_LearnerExerciseAttempts_ResponseDuration" CHECK ("ResponseDurationMs" IS NULL OR "ResponseDurationMs" >= 0)
);
CREATE INDEX "IX_LearnerExerciseAttempts_Course_Occurred" ON "LearnerExerciseAttempts" ("LearnerCourseId","OccurredAt" DESC,"Id" DESC);
-- Attempts are immutable activity; do not introduce a second course progress store.
-- LearningUnit/Card/FSRS review, XP and Gamification are distinct existing owners
-- and MUST be modelled and validated before Gate B; this draft doesn't cover them.

COMMIT;
