-- PHASE B WORKING DRAFT, NOT APPROVED BASELINE, NOT APPLIED TO ANY DATABASE.
-- Source: docs/CLEAN_CUT_DATABASE.md §2/§3/§8 and Phase-A domain ownership.
-- All numerical seed IDs in this draft must be reconciled with actual C# byte enum contracts
-- before a migration is generated. No historical IDs/data/backfill assumed.
-- Target: fresh PostgreSQL >= 15 (NULLS NOT DISTINCT required in companion file).
BEGIN;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE "UiLocales" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Locale" varchar(32) NOT NULL,
    "Name" text NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "IsRightToLeft" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_UiLocales" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_UiLocales_Locale" UNIQUE ("Locale"),
    CONSTRAINT "CK_UiLocales_Locale" CHECK (length(btrim("Locale")) > 0)
);

CREATE TABLE "AccountRoleTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_AccountRoleTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AccountRoleTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_AccountRoleTypes_Id" CHECK ("Id" BETWEEN 0 AND 255)
);
-- PROPOSED seed IDs; binding enum values require owner/implementation confirmation.
-- Current Jularr C# AccountRole values are Owner=1, User=2, MediaManager=3.
-- The target byte-contract remains to be signed; keep these proposed numbers
-- aligned to code until an explicit cross-language change is approved.
INSERT INTO "AccountRoleTypes" ("Id", "Key") VALUES (1,'owner'),(2,'user'),(3,'media_manager');

CREATE TABLE "Accounts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Email" citext NOT NULL,
    "DisplayName" text NOT NULL,
    "AccountRoleTypeId" smallint NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "EmailVerifiedAt" timestamptz,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_Accounts_Email" UNIQUE ("Email"),
    CONSTRAINT "FK_Accounts_AccountRoleTypes" FOREIGN KEY ("AccountRoleTypeId") REFERENCES "AccountRoleTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_Accounts_Email" CHECK (length(btrim("Email"::text)) > 0),
    CONSTRAINT "CK_Accounts_DisplayName" CHECK (length(btrim("DisplayName")) > 0)
);

CREATE TABLE "Profiles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OwnerAccountId" bigint NOT NULL,
    "DisplayName" text NOT NULL,
    "UiLocaleId" bigint NOT NULL,
    "PinHash" text,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Profiles_Accounts" FOREIGN KEY ("OwnerAccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Profiles_UiLocales" FOREIGN KEY ("UiLocaleId") REFERENCES "UiLocales" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_Profiles_DisplayName" CHECK (length(btrim("DisplayName")) > 0)
);
CREATE INDEX "IX_Profiles_OwnerAccountId" ON "Profiles" ("OwnerAccountId", "Id");

CREATE TABLE "AccountProfiles" (
    "AccountId" bigint NOT NULL,
    "ProfileId" bigint NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AccountProfiles" PRIMARY KEY ("AccountId", "ProfileId"),
    CONSTRAINT "FK_AccountProfiles_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AccountProfiles_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_AccountProfiles_ProfileId" ON "AccountProfiles" ("ProfileId", "AccountId");

-- Required owner membership is validated at COMMIT; new profile and membership
-- must be created together in Logic, and ownership transfer must keep the new owner linked.
ALTER TABLE "Profiles" ADD CONSTRAINT "FK_Profiles_OwnerAccountProfiles"
    FOREIGN KEY ("OwnerAccountId","Id") REFERENCES "AccountProfiles" ("AccountId","ProfileId")
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "AccountPasswords" (
    "AccountId" bigint NOT NULL,
    "PasswordHash" text NOT NULL,
    "ChangedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AccountPasswords" PRIMARY KEY ("AccountId"),
    CONSTRAINT "FK_AccountPasswords_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AccountPasskeys" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" bigint NOT NULL,
    "CredentialId" bytea NOT NULL,
    "PublicKey" bytea NOT NULL,
    "SignatureCounter" bigint NOT NULL DEFAULT 0,
    "Aaguid" uuid,
    "Transports" text[] NOT NULL DEFAULT ARRAY[]::text[],
    "BackupEligible" boolean,
    "BackedUp" boolean,
    "UserVerificationRequired" boolean,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "LastUsedAt" timestamptz,
    CONSTRAINT "PK_AccountPasskeys" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountPasskeys_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_AccountPasskeys_CredentialId" UNIQUE ("CredentialId"),
    CONSTRAINT "CK_AccountPasskeys_SignatureCounter" CHECK ("SignatureCounter" >= 0),
    CONSTRAINT "CK_AccountPasskeys_BackupState"
        CHECK ("BackedUp" IS DISTINCT FROM true OR "BackupEligible" IS TRUE)
);
CREATE INDEX "IX_AccountPasskeys_AccountId" ON "AccountPasskeys" ("AccountId");

CREATE TABLE "AccountTotpFactors" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" bigint NOT NULL,
    "EncryptedSecret" bytea NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "ConfirmedAt" timestamptz,
    CONSTRAINT "PK_AccountTotpFactors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountTotpFactors_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AccountRecoveryCodes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" bigint NOT NULL,
    "CodeHash" bytea NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UsedAt" timestamptz,
    CONSTRAINT "PK_AccountRecoveryCodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountRecoveryCodes_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_AccountRecoveryCodes_AccountId_CodeHash" UNIQUE ("AccountId","CodeHash")
);

CREATE TABLE "Providers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_Providers" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_Providers_Key" UNIQUE ("Key")
);

CREATE TABLE "AccountExternalLogins" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" bigint NOT NULL,
    "ProviderId" bigint NOT NULL,
    "ExternalAccountId" text NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AccountExternalLogins" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountExternalLogins_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AccountExternalLogins_Providers" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_AccountExternalLogins_Provider_ExternalId" UNIQUE ("ProviderId","ExternalAccountId")
);
CREATE INDEX "IX_AccountExternalLogins_AccountId" ON "AccountExternalLogins" ("AccountId");

CREATE TABLE "AccountAuthChallenges" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" bigint,
    "ChallengeKey" text NOT NULL,
    "TokenHash" bytea NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    "ConsumedAt" timestamptz,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AccountAuthChallenges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountAuthChallenges_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_AccountAuthChallenges_TokenHash" UNIQUE ("TokenHash"),
    CONSTRAINT "CK_AccountAuthChallenges_Expiry" CHECK ("ExpiresAt" > "CreatedAt")
);

CREATE TABLE "AccountSessions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" bigint NOT NULL,
    "ActiveProfileId" bigint,
    "TokenHash" bytea NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    "RevokedAt" timestamptz,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "LastSeenAt" timestamptz,
    CONSTRAINT "PK_AccountSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_AccountSessions_TokenHash" UNIQUE ("TokenHash"),
    CONSTRAINT "FK_AccountSessions_Accounts" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AccountSessions_AccountProfiles" FOREIGN KEY ("AccountId","ActiveProfileId") REFERENCES "AccountProfiles" ("AccountId","ProfileId") ON DELETE RESTRICT,
    CONSTRAINT "CK_AccountSessions_Expiry" CHECK ("ExpiresAt" > "CreatedAt")
);
CREATE INDEX "IX_AccountSessions_AccountId_ExpiresAt" ON "AccountSessions" ("AccountId","ExpiresAt");

CREATE TABLE "MediaTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_MediaTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_MediaTypes_Id" CHECK ("Id" BETWEEN 0 AND 255)
);
-- PROPOSED seeds; exact enum bytes must be frozen before the final baseline.
INSERT INTO "MediaTypes" ("Id","Key") VALUES
(1,'movie'),(2,'series'),(3,'book'),(4,'manga'),(5,'light_novel'),(6,'music'),(7,'game');

CREATE TABLE "Works" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MediaTypeId" smallint NOT NULL,
    "CanonicalTitle" text NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Works" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_Works_Id_MediaTypeId" UNIQUE ("Id","MediaTypeId"),
    CONSTRAINT "FK_Works_MediaTypes" FOREIGN KEY ("MediaTypeId") REFERENCES "MediaTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_Works_CanonicalTitle" CHECK (length(btrim("CanonicalTitle")) > 0)
);
CREATE INDEX "IX_Works_MediaTypeId_CreatedAt_Id" ON "Works" ("MediaTypeId","CreatedAt" DESC,"Id" DESC);

CREATE TABLE "WorkTitles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "UiLocaleId" bigint,
    "Title" text NOT NULL,
    "IsOriginal" boolean NOT NULL DEFAULT false,
    "IsPreferred" boolean NOT NULL DEFAULT false,
    "ProviderId" bigint,
    "SourceReference" text,
    "IsManualOverride" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_WorkTitles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkTitles_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkTitles_UiLocales" FOREIGN KEY ("UiLocaleId") REFERENCES "UiLocales" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkTitles_Providers" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkTitles_Title" CHECK (length(btrim("Title")) > 0)
);
CREATE INDEX "IX_WorkTitles_WorkId_Locale" ON "WorkTitles" ("WorkId","UiLocaleId");
CREATE INDEX "IX_WorkTitles_Title_Trigram" ON "WorkTitles" USING gin ("Title" gin_trgm_ops);

CREATE TABLE "WorkExternalIdentities" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "ProviderId" bigint NOT NULL,
    "ProviderNamespace" text NOT NULL,
    "ExternalId" text NOT NULL,
    "Evidence" jsonb,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_WorkExternalIdentities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkExternalIdentities_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkExternalIdentities_Providers" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_WorkExternalIdentities_NamespacedExternalId" UNIQUE ("ProviderId","ProviderNamespace","ExternalId")
);
CREATE INDEX "IX_WorkExternalIdentities_WorkId" ON "WorkExternalIdentities" ("WorkId");

-- Facts have explicit typed columns. A generic FactKey/Value(JSONB) EAV store is FORBIDDEN.
-- Additional real facts (ratings, age ratings, origin etc.) require typed Phase-B sign-off.
CREATE TABLE "WorkMetadataFacts" (
    "WorkId" bigint NOT NULL,
    "FirstPublishedOn" date,
    "RuntimeMs" bigint,
    "OriginalLanguage" varchar(32),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_WorkMetadataFacts" PRIMARY KEY ("WorkId"),
    CONSTRAINT "FK_WorkMetadataFacts_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkMetadataFacts_Runtime" CHECK ("RuntimeMs" IS NULL OR "RuntimeMs" >= 0)
);

-- Titles live ONLY in WorkTitles, never duplicated in localized facts.
CREATE TABLE "WorkLocalizedValues" (
    "WorkId" bigint NOT NULL,
    "UiLocaleId" bigint NOT NULL,
    "Description" text,
    "Tagline" text,
    CONSTRAINT "PK_WorkLocalizedValues" PRIMARY KEY ("WorkId","UiLocaleId"),
    CONSTRAINT "FK_WorkLocalizedValues_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkLocalizedValues_UiLocales" FOREIGN KEY ("UiLocaleId") REFERENCES "UiLocales" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkLocalizedValues_NonEmpty" CHECK ("Description" IS NOT NULL OR "Tagline" IS NOT NULL)
);

-- Fixed code-owned field catalog, not open-ended user-selectable key/value fields.
CREATE TABLE "WorkFactTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_WorkFactTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkFactTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "WorkFieldProvenance" (
    "WorkId" bigint NOT NULL,
    "WorkFactTypeId" smallint NOT NULL,
    "ProviderId" bigint,
    "SourceReference" text,
    "IsManualOverride" boolean NOT NULL DEFAULT false,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_WorkFieldProvenance" PRIMARY KEY ("WorkId","WorkFactTypeId"),
    CONSTRAINT "FK_WorkFieldProvenance_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkFieldProvenance_WorkFactTypes" FOREIGN KEY ("WorkFactTypeId") REFERENCES "WorkFactTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkFieldProvenance_Providers" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "WorkRelationTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_WorkRelationTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkRelationTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_WorkRelationTypes_Id" CHECK ("Id" BETWEEN 0 AND 255)
);
-- Seed keys/byte IDs are pending owner approval.
CREATE TABLE "WorkRelations" (
    "SourceWorkId" bigint NOT NULL,
    "TargetWorkId" bigint NOT NULL,
    "WorkRelationTypeId" smallint NOT NULL,
    CONSTRAINT "PK_WorkRelations" PRIMARY KEY ("SourceWorkId","TargetWorkId","WorkRelationTypeId"),
    CONSTRAINT "FK_WorkRelations_SourceWorks" FOREIGN KEY ("SourceWorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkRelations_TargetWorks" FOREIGN KEY ("TargetWorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkRelations_WorkRelationTypes" FOREIGN KEY ("WorkRelationTypeId") REFERENCES "WorkRelationTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkRelations_DistinctWorks" CHECK ("SourceWorkId" <> "TargetWorkId")
);
CREATE INDEX "IX_WorkRelations_TargetWorkId" ON "WorkRelations" ("TargetWorkId");

CREATE TABLE "Franchises" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Franchises" PRIMARY KEY ("Id")
);
CREATE TABLE "FranchiseWorks" (
    "FranchiseId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    CONSTRAINT "PK_FranchiseWorks" PRIMARY KEY ("FranchiseId","WorkId"),
    CONSTRAINT "FK_FranchiseWorks_Franchises" FOREIGN KEY ("FranchiseId") REFERENCES "Franchises" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FranchiseWorks_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_FranchiseWorks_WorkId" ON "FranchiseWorks" ("WorkId");

CREATE TABLE "WorkMediaClassificationTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_WorkMediaClassificationTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkMediaClassificationTypes_Key" UNIQUE ("Key")
);
CREATE TABLE "WorkMediaClassifications" (
    "WorkId" bigint NOT NULL,
    "WorkMediaClassificationTypeId" smallint NOT NULL,
    CONSTRAINT "PK_WorkMediaClassifications" PRIMARY KEY ("WorkId","WorkMediaClassificationTypeId"),
    CONSTRAINT "FK_WorkMediaClassifications_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkMediaClassifications_WorkMediaClassificationTypes" FOREIGN KEY ("WorkMediaClassificationTypeId") REFERENCES "WorkMediaClassificationTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "WorkSeasons" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "SeasonNumber" integer NOT NULL,
    "DisplayName" text,
    CONSTRAINT "PK_WorkSeasons" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkSeasons_Id_WorkId" UNIQUE ("Id","WorkId"),
    CONSTRAINT "UX_WorkSeasons_WorkId_SeasonNumber" UNIQUE ("WorkId","SeasonNumber"),
    CONSTRAINT "FK_WorkSeasons_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkSeasons_Number" CHECK ("SeasonNumber" >= 0)
);

CREATE TABLE "WorkEpisodes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "WorkSeasonId" bigint NOT NULL,
    "EpisodeNumber" numeric(9,3),
    "OrderIndex" integer NOT NULL,
    "DisplayName" text,
    CONSTRAINT "PK_WorkEpisodes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkEpisodes_Id_WorkId" UNIQUE ("Id","WorkId"),
    CONSTRAINT "UX_WorkEpisodes_Season_Order" UNIQUE ("WorkSeasonId","OrderIndex"),
    CONSTRAINT "FK_WorkEpisodes_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkEpisodes_WorkSeasons" FOREIGN KEY ("WorkSeasonId","WorkId") REFERENCES "WorkSeasons" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkEpisodes_Order" CHECK ("OrderIndex" >= 0)
);

CREATE TABLE "WorkVolumes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "OrderIndex" integer NOT NULL,
    "DisplayName" text,
    CONSTRAINT "PK_WorkVolumes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkVolumes_Id_WorkId" UNIQUE ("Id","WorkId"),
    CONSTRAINT "UX_WorkVolumes_Work_Order" UNIQUE ("WorkId","OrderIndex"),
    CONSTRAINT "FK_WorkVolumes_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkVolumes_Order" CHECK ("OrderIndex" >= 0)
);

CREATE TABLE "WorkChapters" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "WorkVolumeId" bigint,
    "ChapterNumber" numeric(9,3),
    "OrderIndex" integer NOT NULL,
    "DisplayName" text,
    CONSTRAINT "PK_WorkChapters" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkChapters_Id_WorkId" UNIQUE ("Id","WorkId"),
    CONSTRAINT "FK_WorkChapters_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkChapters_WorkVolumes" FOREIGN KEY ("WorkVolumeId","WorkId") REFERENCES "WorkVolumes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkChapters_Order" CHECK ("OrderIndex" >= 0)
);
CREATE UNIQUE INDEX "UX_WorkChapters_Work_Volume_Order" ON "WorkChapters" ("WorkId","WorkVolumeId","OrderIndex") NULLS NOT DISTINCT;

CREATE TABLE "WorkTracks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "OrderIndex" integer NOT NULL,
    "DisplayName" text,
    CONSTRAINT "PK_WorkTracks" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkTracks_Id_WorkId" UNIQUE ("Id","WorkId"),
    CONSTRAINT "UX_WorkTracks_Work_Order" UNIQUE ("WorkId","OrderIndex"),
    CONSTRAINT "FK_WorkTracks_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkTracks_Order" CHECK ("OrderIndex" >= 0)
);

CREATE TABLE "WorkEditions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "Name" text,
    "Region" varchar(16),
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_WorkEditions" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkEditions_Id_WorkId" UNIQUE ("Id","WorkId"),
    CONSTRAINT "FK_WorkEditions_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_WorkEditions_WorkId" ON "WorkEditions" ("WorkId");

CREATE TABLE "WorkVersions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "WorkEditionId" bigint NOT NULL,
    "VersionLabel" text,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_WorkVersions" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_WorkVersions_Id_WorkId" UNIQUE ("Id","WorkId"),
    CONSTRAINT "FK_WorkVersions_WorkEditions" FOREIGN KEY ("WorkEditionId","WorkId") REFERENCES "WorkEditions" ("Id","WorkId") ON DELETE RESTRICT
);
CREATE INDEX "IX_WorkVersions_Edition" ON "WorkVersions" ("WorkEditionId");

CREATE TABLE "MediaAssetTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_MediaAssetTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaAssetTypes_Key" UNIQUE ("Key")
);
-- Type seed set awaits MediaAsset kind inventory sign-off.

CREATE TABLE "MediaAssets" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkVersionId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "MediaAssetTypeId" smallint NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_MediaAssets" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaAssets_Id_WorkVersionId" UNIQUE ("Id","WorkVersionId"),
    CONSTRAINT "UX_MediaAssets_Id_WorkId" UNIQUE ("Id","WorkId"),
    CONSTRAINT "FK_MediaAssets_WorkVersions" FOREIGN KEY ("WorkVersionId","WorkId") REFERENCES "WorkVersions" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaAssets_MediaAssetTypes" FOREIGN KEY ("MediaAssetTypeId") REFERENCES "MediaAssetTypes" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_MediaAssets_WorkVersionId" ON "MediaAssets" ("WorkVersionId");

CREATE TABLE "LibraryRoots" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DisplayName" text NOT NULL,
    "RootPath" text NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "IsOnline" boolean NOT NULL DEFAULT false,
    "LastCheckedAt" timestamptz,
    CONSTRAINT "PK_LibraryRoots" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LibraryRoots_RootPath" UNIQUE ("RootPath")
);

-- MediaAssets repeats WorkId to enforce its canonical WorkVersion↔Work membership.
-- WorkVersionId is deliberately repeated on the physical file row to permit an FK that
-- prevents assigning another edition/version's StoredFile to a GameRelease.
-- The composite FK, not an application convention, preserves the version identity.
CREATE TABLE "StoredFiles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LibraryRootId" bigint NOT NULL,
    "MediaAssetId" bigint NOT NULL,
    "WorkVersionId" bigint NOT NULL,
    "NormalizedRelativePath" text NOT NULL,
    "SizeBytes" bigint,
    "IsPresent" boolean NOT NULL DEFAULT false,
    "LastSeenAt" timestamptz,
    CONSTRAINT "PK_StoredFiles" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_StoredFiles_Id_WorkVersionId" UNIQUE ("Id","WorkVersionId"),
    CONSTRAINT "UX_StoredFiles_Id_MediaAssetId" UNIQUE ("Id","MediaAssetId"),
    CONSTRAINT "UX_StoredFiles_Root_Path" UNIQUE ("LibraryRootId","NormalizedRelativePath"),
    CONSTRAINT "FK_StoredFiles_LibraryRoots" FOREIGN KEY ("LibraryRootId") REFERENCES "LibraryRoots" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StoredFiles_MediaAssets" FOREIGN KEY ("MediaAssetId","WorkVersionId") REFERENCES "MediaAssets" ("Id","WorkVersionId") ON DELETE RESTRICT,
    CONSTRAINT "CK_StoredFiles_SizeBytes" CHECK ("SizeBytes" IS NULL OR "SizeBytes" >= 0),
    CONSTRAINT "CK_StoredFiles_Path" CHECK (length("NormalizedRelativePath") > 0)
);
CREATE INDEX "IX_StoredFiles_MediaAssetId" ON "StoredFiles" ("MediaAssetId");

CREATE TABLE "MediaTrackTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_MediaTrackTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaTrackTypes_Key" UNIQUE ("Key")
);
-- Seed set awaits player/subtitle owner sign-off.
CREATE TABLE "MediaTracks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StoredFileId" bigint NOT NULL,
    "MediaTrackTypeId" smallint NOT NULL,
    "StreamIndex" integer NOT NULL,
    "Language" varchar(32),
    "Codec" text,
    CONSTRAINT "PK_MediaTracks" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_MediaTracks_File_Stream" UNIQUE ("StoredFileId","StreamIndex"),
    CONSTRAINT "FK_MediaTracks_StoredFiles" FOREIGN KEY ("StoredFileId") REFERENCES "StoredFiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaTracks_MediaTrackTypes" FOREIGN KEY ("MediaTrackTypeId") REFERENCES "MediaTrackTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_MediaTracks_StreamIndex" CHECK ("StreamIndex" >= 0)
);
CREATE INDEX "IX_MediaTracks_File_Type_Language" ON "MediaTracks" ("StoredFileId","MediaTrackTypeId","Language");

CREATE TABLE "GamePlatforms" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_GamePlatforms" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_GamePlatforms_Key" UNIQUE ("Key")
);
-- WorkId is a constrained duplicate of WorkVersions.WorkId, NOT a second Game root.
-- Proposal: MediaTypes(game)=7. B01 MUST freeze enum : byte values before baseline.
-- A constant generated discriminator plus two composite FK paths enforce BOTH:
-- (1) the chosen WorkVersion belongs to the Work; and (2) the Work is a game.
CREATE TABLE "GameReleases" (
    "WorkVersionId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "GameMediaTypeId" smallint GENERATED ALWAYS AS (7::smallint) STORED,
    "GamePlatformId" bigint NOT NULL,
    "Region" varchar(16),
    "RevisionLabel" text,
    "LauncherMetadata" jsonb,
    CONSTRAINT "PK_GameReleases" PRIMARY KEY ("WorkVersionId"),
    CONSTRAINT "FK_GameReleases_WorkVersions" FOREIGN KEY ("WorkVersionId","WorkId") REFERENCES "WorkVersions" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_GameReleases_GameWorks" FOREIGN KEY ("WorkId","GameMediaTypeId") REFERENCES "Works" ("Id","MediaTypeId") ON DELETE RESTRICT,
    CONSTRAINT "FK_GameReleases_GamePlatforms" FOREIGN KEY ("GamePlatformId") REFERENCES "GamePlatforms" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_GameReleases_GamePlatformId" ON "GameReleases" ("GamePlatformId");

CREATE TABLE "GameReleaseFileRoleTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_GameReleaseFileRoleTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_GameReleaseFileRoleTypes_Key" UNIQUE ("Key")
);
-- Exact file roles and enum seeds are not yet owner-approved.
-- Every GameReleaseStoredFiles row is constrained to a StoredFile whose
-- MediaAsset belongs to precisely the same WorkVersionId.
CREATE TABLE "GameReleaseStoredFiles" (
    "WorkVersionId" bigint NOT NULL,
    "StoredFileId" bigint NOT NULL,
    "DiscNumber" integer NOT NULL DEFAULT 1,
    "SequenceNumber" integer NOT NULL DEFAULT 0,
    "GameReleaseFileRoleTypeId" smallint NOT NULL,
    CONSTRAINT "PK_GameReleaseStoredFiles" PRIMARY KEY ("WorkVersionId","StoredFileId"),
    CONSTRAINT "FK_GameReleaseStoredFiles_GameReleases" FOREIGN KEY ("WorkVersionId") REFERENCES "GameReleases" ("WorkVersionId") ON DELETE RESTRICT,
    CONSTRAINT "FK_GameReleaseStoredFiles_StoredFiles" FOREIGN KEY ("StoredFileId","WorkVersionId") REFERENCES "StoredFiles" ("Id","WorkVersionId") ON DELETE RESTRICT,
    CONSTRAINT "FK_GameReleaseStoredFiles_GameReleaseFileRoleTypes" FOREIGN KEY ("GameReleaseFileRoleTypeId") REFERENCES "GameReleaseFileRoleTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_GameReleaseStoredFiles_Disc" CHECK ("DiscNumber" >= 1),
    CONSTRAINT "CK_GameReleaseStoredFiles_Sequence" CHECK ("SequenceNumber" >= 0)
);
CREATE INDEX "IX_GameReleaseStoredFiles_StoredFileId" ON "GameReleaseStoredFiles" ("StoredFileId");

CREATE TABLE "StoredFileHashes" (
    "StoredFileId" bigint NOT NULL,
    "AlgorithmKey" text NOT NULL,
    "HashValue" text NOT NULL,
    "VerifiedAt" timestamptz,
    CONSTRAINT "PK_StoredFileHashes" PRIMARY KEY ("StoredFileId","AlgorithmKey"),
    CONSTRAINT "FK_StoredFileHashes_StoredFiles" FOREIGN KEY ("StoredFileId") REFERENCES "StoredFiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_StoredFileHashes_Hash" CHECK (length("HashValue") > 0)
);
COMMIT;
