-- PHASE B DRAFT 09: profile-private Learning activity + optional Gamification.
-- Source: docs/LEARNING_GAMIFICATION.md (binding product plan).
-- NEVER use global Operations/JularrEvent as a high-frequency Learning activity ledger.
-- No new XP balance, derived streak counter, badge-progress, heartbeat or currency.
-- Execute only after drafts 01..08 on a fresh disposable PostgreSQL database.
-- All type IDs/keys require final byte enum seed signoff; NO old enum IDs implied.
BEGIN;

CREATE TABLE "LearningActivityKindTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningActivityKindTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningActivityKindTypes_Key" UNIQUE ("Key")
);
-- Lesson, Review, VocabularyPractice, SentencePractice, ScriptPractice, MediaPractice.
CREATE TABLE "LearningSessionEndReasonTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningSessionEndReasonTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningSessionEndReasonTypes_Key" UNIQUE ("Key")
);
-- Completed, Exited, Abandoned. Session existence does NOT mean course completion.

CREATE TABLE "LearningActivitySessions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ClientSessionId" uuid NOT NULL,
    "ProfileId" bigint NOT NULL,
    "LearningActivityKindTypeId" smallint NOT NULL,
    "LanguageTag" varchar(35),
    "LearnerCourseId" uuid,
    "LearningCourseId" bigint,
    "CurriculumLessonId" uuid,
    "StartedAt" timestamptz NOT NULL,
    "LastActivityAt" timestamptz NOT NULL,
    "EndedAt" timestamptz,
    "LearningSessionEndReasonTypeId" smallint,
    "ClientActiveMilliseconds" bigint NOT NULL DEFAULT 0,
    "ActiveSeconds" bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_LearningActivitySessions" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningActivitySessions_Id_ProfileId" UNIQUE ("Id","ProfileId"),
    CONSTRAINT "UX_LearningActivitySessions_Profile_ClientSession" UNIQUE ("ProfileId","ClientSessionId"),
    CONSTRAINT "FK_LearningActivitySessions_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningActivitySessions_LearningActivityKindTypes" FOREIGN KEY ("LearningActivityKindTypeId") REFERENCES "LearningActivityKindTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningActivitySessions_LearnerCourses" FOREIGN KEY ("LearnerCourseId","ProfileId") REFERENCES "LearnerCourses" ("Id","ProfileId") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningActivitySessions_LearningCourses" FOREIGN KEY ("LearningCourseId","ProfileId") REFERENCES "LearningCourses" ("Id","ProfileId") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningActivitySessions_CurriculumLessons" FOREIGN KEY ("CurriculumLessonId") REFERENCES "CurriculumLessons" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningActivitySessions_EndReasonTypes" FOREIGN KEY ("LearningSessionEndReasonTypeId") REFERENCES "LearningSessionEndReasonTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningActivitySessions_Scope" CHECK (num_nonnulls("LearnerCourseId","LearningCourseId") <= 1),
    CONSTRAINT "CK_LearningActivitySessions_Time" CHECK (
        "LastActivityAt" >= "StartedAt" AND ("EndedAt" IS NULL OR "EndedAt" >= "StartedAt")),
    CONSTRAINT "CK_LearningActivitySessions_Active" CHECK ("ClientActiveMilliseconds" >= 0 AND "ActiveSeconds" >= 0)
);
CREATE INDEX "IX_LearningActivitySessions_Profile_Started" ON "LearningActivitySessions"
    ("ProfileId","StartedAt" DESC,"Id" DESC);
-- LearnerCourseId/ProfileId is now guaranteed via the composite FK.
-- CurriculumLessonId pinned Blueprint membership still requires a relational
-- or transactionally-locked domain check before Phase B signoff.

CREATE TABLE "LearningSessionTimeSlices" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LearningActivitySessionId" bigint NOT NULL,
    "LocalDate" date NOT NULL,
    "ActiveSeconds" bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_LearningSessionTimeSlices" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningSessionTimeSlices_Session_Day" UNIQUE ("LearningActivitySessionId","LocalDate"),
    CONSTRAINT "FK_LearningSessionTimeSlices_LearningActivitySessions" FOREIGN KEY ("LearningActivitySessionId") REFERENCES "LearningActivitySessions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningSessionTimeSlices_Active" CHECK ("ActiveSeconds" >= 0)
);
-- Profile local date derives from canonical profile time zone/region settings,
-- not an independent Learning-specific TimeZone.
-- Logic must reject duplicate/decreasing monotonic active-time counters and clamp
-- accepted deltas to plausible elapsed wall time + small transport tolerance.
-- No heartbeat event persistence.

CREATE TABLE "LearningActivityEventKindTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_LearningActivityEventKindTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningActivityEventKindTypes_Key" UNIQUE ("Key")
);
-- ExerciseCompleted / ReviewCompleted / LessonCompleted /
-- PracticeItemCompleted / SessionCompleted. NOT JularrEvent notifications.

CREATE TABLE "LearningActivityEvents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LearningActivitySessionId" bigint NOT NULL,
    "ProfileId" bigint NOT NULL,
    "SourceEventId" uuid NOT NULL,
    "LearningActivityEventKindTypeId" smallint NOT NULL,
    "OccurredAt" timestamptz NOT NULL,
    "XpAwarded" integer NOT NULL DEFAULT 0,
    "XpPolicyVersion" integer NOT NULL,
    CONSTRAINT "PK_LearningActivityEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LearningActivityEvents_LearningActivitySessions" FOREIGN KEY ("LearningActivitySessionId","ProfileId") REFERENCES "LearningActivitySessions" ("Id","ProfileId") ON DELETE RESTRICT,
    CONSTRAINT "FK_LearningActivityEvents_LearningActivityEventKindTypes" FOREIGN KEY ("LearningActivityEventKindTypeId") REFERENCES "LearningActivityEventKindTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_LearningActivityEvents_Profile_Event_Kind" UNIQUE ("ProfileId","SourceEventId","LearningActivityEventKindTypeId"),
    CONSTRAINT "CK_LearningActivityEvents_Xp" CHECK ("XpAwarded" >= 0 AND "XpPolicyVersion" >= 1)
);
CREATE INDEX "IX_LearningActivityEvents_Profile_Occurred" ON "LearningActivityEvents"
    ("ProfileId","OccurredAt" DESC,"Id" DESC);
-- XP rules use ONE versioned code policy. XP is stored only here; source idempotency
-- and gamification preference OFF must be checked atomically with the learning action.

CREATE TABLE "LearningGamificationPreferences" (
    "ProfileId" bigint NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT false,
    "DailyXpTarget" integer,
    "DailyActiveMinutes" integer,
    "DailySessionsTarget" integer,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearningGamificationPreferences" PRIMARY KEY ("ProfileId"),
    CONSTRAINT "FK_LearningGamificationPreferences_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningGamificationPreferences_Targets" CHECK (
        ("DailyXpTarget" IS NULL OR "DailyXpTarget" > 0) AND
        ("DailyActiveMinutes" IS NULL OR "DailyActiveMinutes" > 0) AND
        ("DailySessionsTarget" IS NULL OR "DailySessionsTarget" > 0))
);

CREATE TABLE "LearningDailyGoals" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "LocalDate" date NOT NULL,
    "XpTarget" integer,
    "ActiveSecondsTarget" integer,
    "SessionsTarget" integer,
    "CompletedAt" timestamptz,
    CONSTRAINT "PK_LearningDailyGoals" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_LearningDailyGoals_Profile_Day" UNIQUE ("ProfileId","LocalDate"),
    CONSTRAINT "FK_LearningDailyGoals_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_LearningDailyGoals_Targets" CHECK (
        ("XpTarget" IS NULL OR "XpTarget" > 0) AND
        ("ActiveSecondsTarget" IS NULL OR "ActiveSecondsTarget" > 0) AND
        ("SessionsTarget" IS NULL OR "SessionsTarget" > 0))
);
-- Create goal snapshot ONLY at the first active gamified day. Never mutate
-- today's snapshotted targets when the user edits preferences.
-- Streak is derived from completed days. No streak balance/counter table.

CREATE TABLE "LearningAchievementUnlocks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "DefinitionKey" varchar(120) NOT NULL,
    "DefinitionVersion" integer NOT NULL,
    "UnlockedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LearningAchievementUnlocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LearningAchievementUnlocks_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_LearningAchievementUnlocks_Profile_Definition" UNIQUE ("ProfileId","DefinitionKey","DefinitionVersion"),
    CONSTRAINT "CK_LearningAchievementUnlocks_Version" CHECK ("DefinitionVersion" >= 1),
    CONSTRAINT "CK_LearningAchievementUnlocks_Key" CHECK (length(btrim("DefinitionKey")) > 0)
);
-- Achievement definitions and XP level thresholds are versioned code/domain policy;
-- no editable achievement catalog and no mutable progress counters.

COMMIT;
