-- PHASE B DRAFT 06: Offline event idempotence and consented provider-media connections.
-- Sources: docs/CLEAN_CUT_DATABASE.md, PR #920 PlexProfileConnectionStore / PlexServerGrantStore,
-- PR #937 Jellyfin read adapter, docs/LEARNING_PROGRESS.md (separate learner idempotence).
-- Non-secret persistence only. Protected provider tokens/credentials stay in the
-- existing protected /data contract until a distinct credential-storage decision.
-- NO database reset or production execution.
BEGIN;

-- (Id, ProfileId) is a candidate key for a durable, profile-scoped FK.
ALTER TABLE "MediaProgress" ADD CONSTRAINT "UX_MediaProgress_Id_ProfileId" UNIQUE ("Id","ProfileId");
CREATE TABLE "MediaProgressCheckpointEvents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "MediaProgressId" bigint NOT NULL,
    "ClientEventId" uuid NOT NULL,
    "AcceptedRevision" bigint NOT NULL,
    "ClientOccurredAt" timestamptz,
    "AcceptedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_MediaProgressCheckpointEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaProgressCheckpointEvents_MediaProgress" FOREIGN KEY ("MediaProgressId","ProfileId") REFERENCES "MediaProgress" ("Id","ProfileId") ON DELETE RESTRICT,
    CONSTRAINT "FK_MediaProgressCheckpointEvents_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_MediaProgressCheckpointEvents_Profile_EventId" UNIQUE ("ProfileId","ClientEventId"),
    CONSTRAINT "CK_MediaProgressCheckpointEvents_Revision" CHECK ("AcceptedRevision" >= 1)
);
CREATE INDEX "IX_MediaProgressCheckpointEvents_Progress_Accepted" ON "MediaProgressCheckpointEvents" ("MediaProgressId","AcceptedAt" DESC,"Id" DESC);
-- Service+Logic MUST check event uniqueness and optimistic revision within the same
-- transaction as its target MediaProgress and corresponding Time/Reading/Game detail.
-- Neither a repeated event nor an older client revision may mutate the current row.

-- Login external identity belongs to AccountExternalLogins; provider/media
-- connection consent belongs to an explicitly selected Profile, never automatic login.
CREATE TABLE "ProviderMediaConnections" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" bigint NOT NULL,
    "ProviderId" bigint NOT NULL,
    "ExternalAccountId" text NOT NULL,
    "ConsentedAt" timestamptz NOT NULL,
    "CredentialsStorageKey" text NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "IsWatchlistSyncEnabled" boolean NOT NULL DEFAULT false,
    "IsProgressSyncEnabled" boolean NOT NULL DEFAULT false,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ProviderMediaConnections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProviderMediaConnections_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProviderMediaConnections_Providers" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_ProviderMediaConnections_Profile_Provider" UNIQUE ("ProfileId","ProviderId"),
    CONSTRAINT "CK_ProviderMediaConnections_Account" CHECK (length(btrim("ExternalAccountId")) > 0),
    CONSTRAINT "CK_ProviderMediaConnections_StorageKey" CHECK (length(btrim("CredentialsStorageKey")) > 0)
);
-- CredentialsStorageKey is a server-owned opaque reference, NOT plaintext access token,
-- provider URL, signed stream URL or user-controlled filesystem path.
CREATE TABLE "ProviderServerGrants" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProviderId" bigint NOT NULL,
    "ExternalServerId" text NOT NULL,
    "DisplayName" text NOT NULL,
    "CredentialsStorageKey" text NOT NULL,
    "ApprovedByAccountId" bigint NOT NULL,
    "ApprovedAt" timestamptz NOT NULL DEFAULT now(),
    "IsEnabled" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_ProviderServerGrants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProviderServerGrants_Providers" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProviderServerGrants_Accounts" FOREIGN KEY ("ApprovedByAccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_ProviderServerGrants_Provider_Server" UNIQUE ("ProviderId","ExternalServerId"),
    CONSTRAINT "CK_ProviderServerGrants_ServerId" CHECK (length(btrim("ExternalServerId")) > 0)
);
CREATE TABLE "ProviderGrantLibrarySections" (
    "ProviderServerGrantId" bigint NOT NULL,
    "ExternalSectionId" text NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_ProviderGrantLibrarySections" PRIMARY KEY ("ProviderServerGrantId","ExternalSectionId"),
    CONSTRAINT "FK_ProviderGrantLibrarySections_ProviderServerGrants" FOREIGN KEY ("ProviderServerGrantId") REFERENCES "ProviderServerGrants" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_ProviderGrantLibrarySections_SectionId" CHECK (length(btrim("ExternalSectionId")) > 0)
);

-- Nonsecret, resumable catalog progress. Data snapshots/cache may still live
-- under durable /data; this is metadata, never an alternative Work identity.
CREATE TABLE "ProviderCatalogCheckpoints" (
    "ProviderServerGrantId" bigint NOT NULL,
    "ExternalSectionId" text NOT NULL,
    "GenerationId" uuid NOT NULL,
    "NextStart" integer,
    "PageSize" integer NOT NULL,
    "PagesScanned" integer NOT NULL DEFAULT 0,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ProviderCatalogCheckpoints" PRIMARY KEY ("ProviderServerGrantId","ExternalSectionId"),
    CONSTRAINT "FK_ProviderCatalogCheckpoints_ProviderGrantLibrarySections" FOREIGN KEY ("ProviderServerGrantId","ExternalSectionId")
        REFERENCES "ProviderGrantLibrarySections" ("ProviderServerGrantId","ExternalSectionId") ON DELETE RESTRICT,
    CONSTRAINT "CK_ProviderCatalogCheckpoints_Next" CHECK ("NextStart" IS NULL OR "NextStart" >= 0),
    CONSTRAINT "CK_ProviderCatalogCheckpoints_PageSize" CHECK ("PageSize" BETWEEN 1 AND 1000),
    CONSTRAINT "CK_ProviderCatalogCheckpoints_PagesScanned" CHECK ("PagesScanned" >= 0)
);

-- No duplicate AccountExternalLogins row, no separate job queue, no provider
-- watch-history import without an explicit product decision.
COMMIT;
