-- PHASE B, WORKING DRAFT 04: monitoring intent, Wanted, request intent and notifications.
-- Based on Features/Monitoring/CODEMAP.md, Acquisition/Wanted/CODEMAP.md,
-- docs/mockups/admin-notifications/SPEC.md and open notification PR #842.
-- No live-DB change; type seed IDs and exact transport policies NOT approved.
-- Run after parts 01..03 ONLY against an isolated disposable PostgreSQL database.
BEGIN;

-- A missing monitoring row means inherit. No duplicate effective-monitored state.
CREATE TABLE "WorkMonitoringDecisions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "WorkSeasonId" bigint,
    "WorkEpisodeId" bigint,
    "WorkVolumeId" bigint,
    "WorkChapterId" bigint,
    "WorkTrackId" bigint,
    "WorkEditionId" bigint,
    "IsMonitored" boolean NOT NULL,
    CONSTRAINT "PK_WorkMonitoringDecisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkMonitoringDecisions_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkMonitoringDecisions_WorkSeasons" FOREIGN KEY ("WorkSeasonId","WorkId") REFERENCES "WorkSeasons" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkMonitoringDecisions_WorkEpisodes" FOREIGN KEY ("WorkEpisodeId","WorkId") REFERENCES "WorkEpisodes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkMonitoringDecisions_WorkVolumes" FOREIGN KEY ("WorkVolumeId","WorkId") REFERENCES "WorkVolumes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkMonitoringDecisions_WorkChapters" FOREIGN KEY ("WorkChapterId","WorkId") REFERENCES "WorkChapters" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkMonitoringDecisions_WorkTracks" FOREIGN KEY ("WorkTrackId","WorkId") REFERENCES "WorkTracks" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkMonitoringDecisions_WorkEditions" FOREIGN KEY ("WorkEditionId","WorkId") REFERENCES "WorkEditions" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "CK_WorkMonitoringDecisions_OneTarget" CHECK (
        num_nonnulls("WorkSeasonId","WorkEpisodeId","WorkVolumeId","WorkChapterId","WorkTrackId","WorkEditionId") <= 1)
);
CREATE UNIQUE INDEX "UX_WorkMonitoringDecisions_Target" ON "WorkMonitoringDecisions"
    ("WorkId","WorkSeasonId","WorkEpisodeId","WorkVolumeId","WorkChapterId","WorkTrackId","WorkEditionId") NULLS NOT DISTINCT;
-- No IsEffective, no modes (Future/All): those are derived decisions/workflows.

-- Concrete request intent persists only for the approved, open request; not inferred later.
ALTER TABLE "AcquisitionRequests" ADD CONSTRAINT "UX_AcquisitionRequests_Id_WorkId" UNIQUE ("Id","WorkId");
CREATE TABLE "AcquisitionRequestTargets" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AcquisitionRequestId" bigint NOT NULL,
    "WorkId" bigint NOT NULL,
    "WorkSeasonId" bigint,
    "WorkEpisodeId" bigint,
    "WorkVolumeId" bigint,
    "WorkChapterId" bigint,
    "WorkTrackId" bigint,
    "WorkEditionId" bigint,
    CONSTRAINT "PK_AcquisitionRequestTargets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AcquisitionRequestTargets_AcquisitionRequests" FOREIGN KEY ("AcquisitionRequestId","WorkId") REFERENCES "AcquisitionRequests" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequestTargets_WorkSeasons" FOREIGN KEY ("WorkSeasonId","WorkId") REFERENCES "WorkSeasons" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequestTargets_WorkEpisodes" FOREIGN KEY ("WorkEpisodeId","WorkId") REFERENCES "WorkEpisodes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequestTargets_WorkVolumes" FOREIGN KEY ("WorkVolumeId","WorkId") REFERENCES "WorkVolumes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequestTargets_WorkChapters" FOREIGN KEY ("WorkChapterId","WorkId") REFERENCES "WorkChapters" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequestTargets_WorkTracks" FOREIGN KEY ("WorkTrackId","WorkId") REFERENCES "WorkTracks" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_AcquisitionRequestTargets_WorkEditions" FOREIGN KEY ("WorkEditionId","WorkId") REFERENCES "WorkEditions" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "CK_AcquisitionRequestTargets_OneTarget" CHECK (
        num_nonnulls("WorkSeasonId","WorkEpisodeId","WorkVolumeId","WorkChapterId","WorkTrackId","WorkEditionId") <= 1)
);
CREATE UNIQUE INDEX "UX_AcquisitionRequestTargets_ExactTarget" ON "AcquisitionRequestTargets"
    ("AcquisitionRequestId","WorkSeasonId","WorkEpisodeId","WorkVolumeId","WorkChapterId","WorkTrackId","WorkEditionId") NULLS NOT DISTINCT;

-- Exactly one canonical wanted row for each missing/upgrade target.
-- "missing" vs "upgrade" is resolved from held coverage, never duplicated in this table.
CREATE TABLE "WantedItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkId" bigint NOT NULL,
    "WorkSeasonId" bigint,
    "WorkEpisodeId" bigint,
    "WorkVolumeId" bigint,
    "WorkChapterId" bigint,
    "WorkTrackId" bigint,
    "WorkEditionId" bigint,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_WantedItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WantedItems_Works" FOREIGN KEY ("WorkId") REFERENCES "Works" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WantedItems_WorkSeasons" FOREIGN KEY ("WorkSeasonId","WorkId") REFERENCES "WorkSeasons" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WantedItems_WorkEpisodes" FOREIGN KEY ("WorkEpisodeId","WorkId") REFERENCES "WorkEpisodes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WantedItems_WorkVolumes" FOREIGN KEY ("WorkVolumeId","WorkId") REFERENCES "WorkVolumes" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WantedItems_WorkChapters" FOREIGN KEY ("WorkChapterId","WorkId") REFERENCES "WorkChapters" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WantedItems_WorkTracks" FOREIGN KEY ("WorkTrackId","WorkId") REFERENCES "WorkTracks" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "FK_WantedItems_WorkEditions" FOREIGN KEY ("WorkEditionId","WorkId") REFERENCES "WorkEditions" ("Id","WorkId") ON DELETE RESTRICT,
    CONSTRAINT "CK_WantedItems_OneTarget" CHECK (
        num_nonnulls("WorkSeasonId","WorkEpisodeId","WorkVolumeId","WorkChapterId","WorkTrackId","WorkEditionId") <= 1)
);
CREATE UNIQUE INDEX "UX_WantedItems_ExactTarget" ON "WantedItems"
    ("WorkId","WorkSeasonId","WorkEpisodeId","WorkVolumeId","WorkChapterId","WorkTrackId","WorkEditionId") NULLS NOT DISTINCT;
CREATE INDEX "IX_WantedItems_CreatedAt" ON "WantedItems" ("CreatedAt","Id");
-- WantedReconciler is the ONLY writer. Operations is the shared execution queue.

-- Current event catalog is defined by code and translated by UiTranslationMessages.
-- No second user notification preference model and no automatic push/email delivery claims.
CREATE TABLE "NotificationEventCategoryTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_NotificationEventCategoryTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_NotificationEventCategoryTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_NotificationEventCategoryTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_NotificationEventCategoryTypes_Key" CHECK (length(btrim("Key")) > 0)
);
CREATE TABLE "NotificationChannelTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_NotificationChannelTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_NotificationChannelTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_NotificationChannelTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_NotificationChannelTypes_Key" CHECK (length(btrim("Key")) > 0)
);
CREATE TABLE "NotificationTimingTypes" (
    "Id" smallint NOT NULL,
    "Key" text NOT NULL,
    CONSTRAINT "PK_NotificationTimingTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "UX_NotificationTimingTypes_Key" UNIQUE ("Key"),
    CONSTRAINT "CK_NotificationTimingTypes_Id" CHECK ("Id" BETWEEN 0 AND 255),
    CONSTRAINT "CK_NotificationTimingTypes_Key" CHECK (length(btrim("Key")) > 0)
);
CREATE TABLE "NotificationSubscriptions" (
    "ProfileId" bigint NOT NULL,
    "NotificationEventCategoryTypeId" smallint NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "NotificationTimingTypeId" smallint NOT NULL,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_NotificationSubscriptions" PRIMARY KEY ("ProfileId","NotificationEventCategoryTypeId"),
    CONSTRAINT "FK_NotificationSubscriptions_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_NotificationSubscriptions_NotificationEventCategoryTypes" FOREIGN KEY ("NotificationEventCategoryTypeId") REFERENCES "NotificationEventCategoryTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_NotificationSubscriptions_NotificationTimingTypes" FOREIGN KEY ("NotificationTimingTypeId") REFERENCES "NotificationTimingTypes" ("Id") ON DELETE RESTRICT
);
CREATE TABLE "NotificationSubscriptionChannels" (
    "ProfileId" bigint NOT NULL,
    "NotificationEventCategoryTypeId" smallint NOT NULL,
    "NotificationChannelTypeId" smallint NOT NULL,
    CONSTRAINT "PK_NotificationSubscriptionChannels" PRIMARY KEY ("ProfileId","NotificationEventCategoryTypeId","NotificationChannelTypeId"),
    CONSTRAINT "FK_NotificationSubscriptionChannels_NotificationSubscriptions" FOREIGN KEY ("ProfileId","NotificationEventCategoryTypeId")
        REFERENCES "NotificationSubscriptions" ("ProfileId","NotificationEventCategoryTypeId") ON DELETE RESTRICT,
    CONSTRAINT "FK_NotificationSubscriptionChannels_NotificationChannelTypes" FOREIGN KEY ("NotificationChannelTypeId") REFERENCES "NotificationChannelTypes" ("Id") ON DELETE RESTRICT
);
CREATE TABLE "NotificationProfileChannels" (
    "ProfileId" bigint NOT NULL,
    "NotificationChannelTypeId" smallint NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_NotificationProfileChannels" PRIMARY KEY ("ProfileId","NotificationChannelTypeId"),
    CONSTRAINT "FK_NotificationProfileChannels_Profiles" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_NotificationProfileChannels_NotificationChannelTypes" FOREIGN KEY ("NotificationChannelTypeId") REFERENCES "NotificationChannelTypes" ("Id") ON DELETE RESTRICT
);
-- The real sink registry still determines usable channels. Preference rows do NOT
-- imply an enabled or available external transport. Absence => default In-App.

COMMIT;
